/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VscoRouteImport } from './routes/vsco'
import { Route as TiktokRouteImport } from './routes/tiktok'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SnapchatRouteImport } from './routes/snapchat'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HighlightRouteImport } from './routes/highlight'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'

const VscoRoute = VscoRouteImport.update({
  id: '/vsco',
  path: '/vsco',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokRoute = TiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapchatRoute = SnapchatRouteImport.update({
  id: '/snapchat',
  path: '/snapchat',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HighlightRoute = HighlightRouteImport.update({
  id: '/highlight',
  path: '/highlight',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/highlight': typeof HighlightRoute
  '/history': typeof HistoryRoute
  '/instagram': typeof InstagramRoute
  '/snapchat': typeof SnapchatRoute
  '/story': typeof StoryRoute
  '/tiktok': typeof TiktokRoute
  '/vsco': typeof VscoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/highlight': typeof HighlightRoute
  '/history': typeof HistoryRoute
  '/instagram': typeof InstagramRoute
  '/snapchat': typeof SnapchatRoute
  '/story': typeof StoryRoute
  '/tiktok': typeof TiktokRoute
  '/vsco': typeof VscoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/highlight': typeof HighlightRoute
  '/history': typeof HistoryRoute
  '/instagram': typeof InstagramRoute
  '/snapchat': typeof SnapchatRoute
  '/story': typeof StoryRoute
  '/tiktok': typeof TiktokRoute
  '/vsco': typeof VscoRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/highlight'
    | '/history'
    | '/instagram'
    | '/snapchat'
    | '/story'
    | '/tiktok'
    | '/vsco'
    | '/demo/tanstack-query'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/highlight'
    | '/history'
    | '/instagram'
    | '/snapchat'
    | '/story'
    | '/tiktok'
    | '/vsco'
    | '/demo/tanstack-query'
    | '/demo/form/address'
    | '/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/highlight'
    | '/history'
    | '/instagram'
    | '/snapchat'
    | '/story'
    | '/tiktok'
    | '/vsco'
    | '/demo/tanstack-query'
    | '/demo/form/address'
    | '/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HighlightRoute: typeof HighlightRoute
  HistoryRoute: typeof HistoryRoute
  InstagramRoute: typeof InstagramRoute
  SnapchatRoute: typeof SnapchatRoute
  StoryRoute: typeof StoryRoute
  TiktokRoute: typeof TiktokRoute
  VscoRoute: typeof VscoRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vsco': {
      id: '/vsco'
      path: '/vsco'
      fullPath: '/vsco'
      preLoaderRoute: typeof VscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok': {
      id: '/tiktok'
      path: '/tiktok'
      fullPath: '/tiktok'
      preLoaderRoute: typeof TiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapchat': {
      id: '/snapchat'
      path: '/snapchat'
      fullPath: '/snapchat'
      preLoaderRoute: typeof SnapchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/highlight': {
      id: '/highlight'
      path: '/highlight'
      fullPath: '/highlight'
      preLoaderRoute: typeof HighlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HighlightRoute: HighlightRoute,
  HistoryRoute: HistoryRoute,
  InstagramRoute: InstagramRoute,
  SnapchatRoute: SnapchatRoute,
  StoryRoute: StoryRoute,
  TiktokRoute: TiktokRoute,
  VscoRoute: VscoRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
