name: Test
on:
  pull_request:
    types:
      - opened
      - closed
      - reopened
  workflow_dispatch:
    inputs: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Source Code
        uses: actions/checkout@v3
      # - name: Install Linux-only Dependencies
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     # sudo apt install -y ubuntu-desktop-minimal
      #     # sudo systemctl isolate graphical
      #     # sudo systemctl start gdm3
      - name: Set-up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19.0"
      - name: Test
        run: make test
        env:
          SESSION: ${{secrets.SESSION}}
          FBSR: ${{secrets.FBSR}}
          USER: ${{secrets.USER}}
          TIKTOK: ${{secrets.TIKTOK}}