# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: raker
builds:
  - id: linux
    env: [CGO_ENABLED=0]
    main: ./server
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X 'github.com/AppleGamer22/{{.ProjectName}}/shared.Version={{.Version}}'
      - -X 'github.com/AppleGamer22/{{.ProjectName}}/shared.Hash={{.FullCommit}}'
changelog:
  use: github
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore'
    - typo
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
release:
  github:
    owner: AppleGamer22
    name: raker
  discussion_category_name: General
  prerelease: auto
dockers:
  - use: buildx
    goarch: amd64
    image_templates:
      - docker.io/applegamer22/{{.ProjectName}}:{{.Version}}-amd64
      - ghcr.io/applegamer22/{{.ProjectName}}:{{.Version}}-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
  - use: buildx
    goarch: arm64
    image_templates:
      - docker.io/applegamer22/{{.ProjectName}}:{{.Version}}-arm64
      - ghcr.io/applegamer22/{{.ProjectName}}:{{.Version}}-arm64
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
docker_manifests:
  - name_template: docker.io/applegamer22/{{.ProjectName}}:{{.Version}}
    image_templates:
      - docker.io/applegamer22/{{.ProjectName}}:{{.Version}}-amd64
      - docker.io/applegamer22/{{.ProjectName}}:{{.Version}}-arm64
  - name_template: ghcr.io/applegamer22/{{.ProjectName}}:{{.Version}}
    image_templates:
      - ghcr.io/applegamer22/{{.ProjectName}}:{{.Version}}-amd64
      - ghcr.io/applegamer22/{{.ProjectName}}:{{.Version}}-arm64
sboms:
  - artifacts: archive