# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: raker
version: 2
# before:
#   hooks:
#     - make completion manual
builds:
  - id: linux
    dir: cli
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      # - riscv64
    ldflags:
      - -X 'github.com/AppleGamer22/raker/cmd.Version={{.Version}}'
      - -X 'github.com/AppleGamer22/raker/cmd.Hash={{.FullCommit}}'
  # - id: mac
  #   dir: cli
  #   goos:
  #     - darwin
  #   goarch:
  #     - amd64
  #     - arm64
  #   ldflags:
  #     - -X 'github.com/AppleGamer22/raker/cmd.Version={{.Version}}'
  #     - -X 'github.com/AppleGamer22/raker/cmd.Hash={{.FullCommit}}'
  #   skip: true
  # - id: windows
  #   dir: cli
  #   goos:
  #     - windows
  #   goarch:
  #     - amd64
  #     - arm64
  #   ldflags:
  #     - -X 'github.com/AppleGamer22/raker/cmd.Version={{.Version}}'
  #     - -X 'github.com/AppleGamer22/raker/cmd.Hash={{.FullCommit}}'
# archives:
#   - id: unix
#     builds:
#       - linux
#       - mac
#     name_template: >-
#       {{- .ProjectName}}_
#       {{- .Version}}_
#       {{- if eq .Os "darwin"}}mac{{else}}
#         {{- .Os}}
#       {{- end}}_
#       {{- .Arch}}
#     files:
#       - raker.bash
#       - raker.fish
#       - raker.zsh
#       - raker.1
#   - id: windows
#     builds:
#       - windows
#     format_overrides:
#       - goos: windows
#         format: zip
#     name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
#     files:
#       - raker.ps1
#       - raker.1
# nfpms:
#   - package_name: raker
#     vendor: AppleGamer22
#     maintainer: Omri Bornstein <omribor@gmail.com>
#     homepage: https://github.com/AppleGamer22/raker
#     license: GPL-3.0
#     description: A social media scraper with less JavaScript than my previous one.
#     file_name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
#     builds:
#       - linux
#     dependencies:
#       - chromium
#     formats:
#       - apk
#       - deb
#       - rpm
#       - archlinux
#     contents:
#       - src: raker.1
#         dst: /usr/share/man/man1/raker.1
#         file_info:
#           mode: 0644
#       - src: raker.bash
#         dst: /usr/share/bash-completion/completions/raker
#       - src: raker.fish
#         dst: /usr/share/fish/completions/raker.fish
#       - src: raker.zsh
#         dst: /usr/share/zsh/site-functions/_raker
changelog:
  use: github
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore'
    - typo
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999
release:
  github:
    owner: AppleGamer22
    name: raker
  discussion_category_name: General
  footer: |
    ## Installation
    ### Arch Linux Distributions
    * [`yay`](https://github.com/Jguer/yay):
    ```bash
    yay -S raker-bin
    ```
    * [`paru`](https://github.com/morganamilo/paru):
    ```bash
    paru -S raker-bin
    ```

    ### macOS
    * [Homebrew Tap](https://github.com/AppleGamer22/homebrew-raker):
    ```bash
    brew install AppleGamer22/tap/raker
    ```
  prerelease: auto
dockers:
  - use: buildx
    image_templates:
      - docker.io/applegamer22/{{.ProjectName}}:{{.Version}}-amd64
      # - docker.io/applegamer22/{{.ProjectName}}:latest-amd64
      - ghcr.io/applegamer22/{{.ProjectName}}:{{.Version}}-amd64
      # - ghcr.io/applegamer22/{{.ProjectName}}:latest-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
  - use: buildx
    image_templates:
      - docker.io/applegamer22/{{.ProjectName}}:{{.Version}}-arm64
      # - docker.io/applegamer22/{{.ProjectName}}:latest-arm64
      - ghcr.io/applegamer22/{{.ProjectName}}:{{.Version}}-arm64
      # - ghcr.io/applegamer22/{{.ProjectName}}:latest-arm64
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
docker_manifests:
  - name_template: docker.io/applegamer22/{{.ProjectName}}:{{.Version}}
    image_templates:
      - docker.io/applegamer22/{{.ProjectName}}:{{.Version}}-amd64"
      - docker.io/applegamer22/{{.ProjectName}}:{{.Version}}-arm64"
  - name_template: ghcr.io/applegamer22/{{.ProjectName}}:{{.Version}}
    image_templates:
      - ghcr.io/applegamer22/{{.ProjectName}}:{{.Version}}-amd64"
      - ghcr.io/applegamer22/{{.ProjectName}}:{{.Version}}-arm64"
# nix:
#   - homepage: https://github.com/AppleGamer22/raker
#     description: A social media scraper with less JavaScript than my previous one.
#     license: GPL3
#     repository:
#       owner: AppleGamer22
#       name: nur
#       token: "{{.Env.TAP_GITHUB_TOKEN}}"
#     commit_author:
#       name: Omri Bornstein
#       email: omribor@gmail.com
#     ids:
#       - unix
#     install: |
#       mkdir -p $out/bin
#       cp -vr ./{{.ProjectName}} $out/bin/{{.ProjectName}}
#       installManPage ./{{.ProjectName}}.1
#     post_install: |
#       installShellCompletion ./{{.ProjectName}}.*sh
# aurs:
#   - homepage: https://github.com/AppleGamer22/raker
#     description: A social media scraper with less JavaScript than my previous one.
#     license: GPL3
#     maintainers:
#       - Omri Bornstein <omribor@gmail.com>
#     contributors:
#       - Omri Bornstein <omribor@gmail.com>
#     private_key: "{{.Env.AUR_SSH_PRIVATE_KEY}}"
#     git_url: ssh://aur@aur.archlinux.org/raker-bin.git
#     depends:
#       - chromium
#     package: |
#       install -Dm755 raker "${pkgdir}/usr/bin/raker"
#       install -Dm644 raker.1 "${pkgdir}/usr/share/man/man1/raker.1"
#       install -Dm644 raker.bash "${pkgdir}/usr/share/bash-completion/completions/raker"
#       install -Dm644 raker.fish "${pkgdir}/usr/share/fish/vendor_completions.d/raker.fish"
#       install -Dm644 raker.zsh "${pkgdir}/usr/share/zsh/site-functions/_raker"
#     commit_author:
#       name: Omri Bornstein
#       email: omribor@gmail.com
# brews:
#   - repository:
#       owner: AppleGamer22
#       name: homebrew-tap
#       token: "{{.Env.TAP_GITHUB_TOKEN}}"
#     download_strategy: CurlDownloadStrategy
#     commit_author:
#       name: Omri Bornstein
#       email: omribor@gmail.com
#     homepage: https://github.com/AppleGamer22/raker
#     dependencies:
#       - chromium
#     description: A social media scraper with less JavaScript than my previous one.
#     license: GPL-3.0
#     install: |
#       bin.install "raker"
#       man1.install "raker.1"
#       bash_completion.install "raker.bash" => "raker"
#       fish_completion.install "raker.fish"
#       zsh_completion.install "raker.zsh" => "_raker"
sboms:
  - artifacts: archive