// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: raker/v1/raker.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/AppleGamer22/raker/server/buf/proto/raker/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RakerServerName is the fully-qualified name of the RakerServer service.
	RakerServerName = "raker.v1.RakerServer"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RakerServerSignUpInstagramProcedure is the fully-qualified name of the RakerServer's
	// SignUpInstagram RPC.
	RakerServerSignUpInstagramProcedure = "/raker.v1.RakerServer/SignUpInstagram"
	// RakerServerSignInInstagramProcedure is the fully-qualified name of the RakerServer's
	// SignInInstagram RPC.
	RakerServerSignInInstagramProcedure = "/raker.v1.RakerServer/SignInInstagram"
	// RakerServerEditCategoryProcedure is the fully-qualified name of the RakerServer's EditCategory
	// RPC.
	RakerServerEditCategoryProcedure = "/raker.v1.RakerServer/EditCategory"
	// RakerServerScrapeInstagramProcedure is the fully-qualified name of the RakerServer's
	// ScrapeInstagram RPC.
	RakerServerScrapeInstagramProcedure = "/raker.v1.RakerServer/ScrapeInstagram"
	// RakerServerScrapeHighlightProcedure is the fully-qualified name of the RakerServer's
	// ScrapeHighlight RPC.
	RakerServerScrapeHighlightProcedure = "/raker.v1.RakerServer/ScrapeHighlight"
	// RakerServerScrapeStoryProcedure is the fully-qualified name of the RakerServer's ScrapeStory RPC.
	RakerServerScrapeStoryProcedure = "/raker.v1.RakerServer/ScrapeStory"
	// RakerServerScrapeTikTokProcedure is the fully-qualified name of the RakerServer's ScrapeTikTok
	// RPC.
	RakerServerScrapeTikTokProcedure = "/raker.v1.RakerServer/ScrapeTikTok"
	// RakerServerScrapeSnapchatProcedure is the fully-qualified name of the RakerServer's
	// ScrapeSnapchat RPC.
	RakerServerScrapeSnapchatProcedure = "/raker.v1.RakerServer/ScrapeSnapchat"
	// RakerServerScrapeVSCOProcedure is the fully-qualified name of the RakerServer's ScrapeVSCO RPC.
	RakerServerScrapeVSCOProcedure = "/raker.v1.RakerServer/ScrapeVSCO"
	// RakerServerRemoveFileProcedure is the fully-qualified name of the RakerServer's RemoveFile RPC.
	RakerServerRemoveFileProcedure = "/raker.v1.RakerServer/RemoveFile"
	// RakerServerUpdateCategoriesProcedure is the fully-qualified name of the RakerServer's
	// UpdateCategories RPC.
	RakerServerUpdateCategoriesProcedure = "/raker.v1.RakerServer/UpdateCategories"
	// RakerServerSearchHistoryProcedure is the fully-qualified name of the RakerServer's SearchHistory
	// RPC.
	RakerServerSearchHistoryProcedure = "/raker.v1.RakerServer/SearchHistory"
	// RakerServerSearchHistoryOwnersProcedure is the fully-qualified name of the RakerServer's
	// SearchHistoryOwners RPC.
	RakerServerSearchHistoryOwnersProcedure = "/raker.v1.RakerServer/SearchHistoryOwners"
)

// RakerServerClient is a client for the raker.v1.RakerServer service.
type RakerServerClient interface {
	SignUpInstagram(context.Context, *v1.SignUpRequest) (*emptypb.Empty, error)
	SignInInstagram(context.Context, *v1.SignUpRequest) (*emptypb.Empty, error)
	EditCategory(context.Context, *v1.EditCategoryRequest) (*emptypb.Empty, error)
	ScrapeInstagram(context.Context, *v1.UnaryScrapeRequest) (*v1.ScrapeResponse, error)
	ScrapeHighlight(context.Context, *v1.UnaryScrapeRequest) (*v1.ScrapeResponse, error)
	ScrapeStory(context.Context, *v1.UnaryScrapeRequest) (*v1.ScrapeResponse, error)
	ScrapeTikTok(context.Context, *v1.BinaryScrapeRequest) (*v1.ScrapeResponse, error)
	ScrapeSnapchat(context.Context, *v1.UnaryScrapeRequest) (*v1.ScrapeResponse, error)
	ScrapeVSCO(context.Context, *v1.BinaryScrapeRequest) (*v1.ScrapeResponse, error)
	RemoveFile(context.Context, *v1.RemoveFileRequest) (*v1.ScrapeResponse, error)
	UpdateCategories(context.Context, *v1.UpdateCategoriesRequest) (*v1.ScrapeResponse, error)
	SearchHistory(context.Context, *v1.HistoryRequest) (*v1.HistoryResponse, error)
	SearchHistoryOwners(context.Context, *v1.HistoryRequest) (*v1.HistoryOwnersResponse, error)
}

// NewRakerServerClient constructs a client for the raker.v1.RakerServer service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRakerServerClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RakerServerClient {
	baseURL = strings.TrimRight(baseURL, "/")
	rakerServerMethods := v1.File_raker_v1_raker_proto.Services().ByName("RakerServer").Methods()
	return &rakerServerClient{
		signUpInstagram: connect.NewClient[v1.SignUpRequest, emptypb.Empty](
			httpClient,
			baseURL+RakerServerSignUpInstagramProcedure,
			connect.WithSchema(rakerServerMethods.ByName("SignUpInstagram")),
			connect.WithClientOptions(opts...),
		),
		signInInstagram: connect.NewClient[v1.SignUpRequest, emptypb.Empty](
			httpClient,
			baseURL+RakerServerSignInInstagramProcedure,
			connect.WithSchema(rakerServerMethods.ByName("SignInInstagram")),
			connect.WithClientOptions(opts...),
		),
		editCategory: connect.NewClient[v1.EditCategoryRequest, emptypb.Empty](
			httpClient,
			baseURL+RakerServerEditCategoryProcedure,
			connect.WithSchema(rakerServerMethods.ByName("EditCategory")),
			connect.WithClientOptions(opts...),
		),
		scrapeInstagram: connect.NewClient[v1.UnaryScrapeRequest, v1.ScrapeResponse](
			httpClient,
			baseURL+RakerServerScrapeInstagramProcedure,
			connect.WithSchema(rakerServerMethods.ByName("ScrapeInstagram")),
			connect.WithClientOptions(opts...),
		),
		scrapeHighlight: connect.NewClient[v1.UnaryScrapeRequest, v1.ScrapeResponse](
			httpClient,
			baseURL+RakerServerScrapeHighlightProcedure,
			connect.WithSchema(rakerServerMethods.ByName("ScrapeHighlight")),
			connect.WithClientOptions(opts...),
		),
		scrapeStory: connect.NewClient[v1.UnaryScrapeRequest, v1.ScrapeResponse](
			httpClient,
			baseURL+RakerServerScrapeStoryProcedure,
			connect.WithSchema(rakerServerMethods.ByName("ScrapeStory")),
			connect.WithClientOptions(opts...),
		),
		scrapeTikTok: connect.NewClient[v1.BinaryScrapeRequest, v1.ScrapeResponse](
			httpClient,
			baseURL+RakerServerScrapeTikTokProcedure,
			connect.WithSchema(rakerServerMethods.ByName("ScrapeTikTok")),
			connect.WithClientOptions(opts...),
		),
		scrapeSnapchat: connect.NewClient[v1.UnaryScrapeRequest, v1.ScrapeResponse](
			httpClient,
			baseURL+RakerServerScrapeSnapchatProcedure,
			connect.WithSchema(rakerServerMethods.ByName("ScrapeSnapchat")),
			connect.WithClientOptions(opts...),
		),
		scrapeVSCO: connect.NewClient[v1.BinaryScrapeRequest, v1.ScrapeResponse](
			httpClient,
			baseURL+RakerServerScrapeVSCOProcedure,
			connect.WithSchema(rakerServerMethods.ByName("ScrapeVSCO")),
			connect.WithClientOptions(opts...),
		),
		removeFile: connect.NewClient[v1.RemoveFileRequest, v1.ScrapeResponse](
			httpClient,
			baseURL+RakerServerRemoveFileProcedure,
			connect.WithSchema(rakerServerMethods.ByName("RemoveFile")),
			connect.WithClientOptions(opts...),
		),
		updateCategories: connect.NewClient[v1.UpdateCategoriesRequest, v1.ScrapeResponse](
			httpClient,
			baseURL+RakerServerUpdateCategoriesProcedure,
			connect.WithSchema(rakerServerMethods.ByName("UpdateCategories")),
			connect.WithClientOptions(opts...),
		),
		searchHistory: connect.NewClient[v1.HistoryRequest, v1.HistoryResponse](
			httpClient,
			baseURL+RakerServerSearchHistoryProcedure,
			connect.WithSchema(rakerServerMethods.ByName("SearchHistory")),
			connect.WithClientOptions(opts...),
		),
		searchHistoryOwners: connect.NewClient[v1.HistoryRequest, v1.HistoryOwnersResponse](
			httpClient,
			baseURL+RakerServerSearchHistoryOwnersProcedure,
			connect.WithSchema(rakerServerMethods.ByName("SearchHistoryOwners")),
			connect.WithClientOptions(opts...),
		),
	}
}

// rakerServerClient implements RakerServerClient.
type rakerServerClient struct {
	signUpInstagram     *connect.Client[v1.SignUpRequest, emptypb.Empty]
	signInInstagram     *connect.Client[v1.SignUpRequest, emptypb.Empty]
	editCategory        *connect.Client[v1.EditCategoryRequest, emptypb.Empty]
	scrapeInstagram     *connect.Client[v1.UnaryScrapeRequest, v1.ScrapeResponse]
	scrapeHighlight     *connect.Client[v1.UnaryScrapeRequest, v1.ScrapeResponse]
	scrapeStory         *connect.Client[v1.UnaryScrapeRequest, v1.ScrapeResponse]
	scrapeTikTok        *connect.Client[v1.BinaryScrapeRequest, v1.ScrapeResponse]
	scrapeSnapchat      *connect.Client[v1.UnaryScrapeRequest, v1.ScrapeResponse]
	scrapeVSCO          *connect.Client[v1.BinaryScrapeRequest, v1.ScrapeResponse]
	removeFile          *connect.Client[v1.RemoveFileRequest, v1.ScrapeResponse]
	updateCategories    *connect.Client[v1.UpdateCategoriesRequest, v1.ScrapeResponse]
	searchHistory       *connect.Client[v1.HistoryRequest, v1.HistoryResponse]
	searchHistoryOwners *connect.Client[v1.HistoryRequest, v1.HistoryOwnersResponse]
}

// SignUpInstagram calls raker.v1.RakerServer.SignUpInstagram.
func (c *rakerServerClient) SignUpInstagram(ctx context.Context, req *v1.SignUpRequest) (*emptypb.Empty, error) {
	response, err := c.signUpInstagram.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SignInInstagram calls raker.v1.RakerServer.SignInInstagram.
func (c *rakerServerClient) SignInInstagram(ctx context.Context, req *v1.SignUpRequest) (*emptypb.Empty, error) {
	response, err := c.signInInstagram.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// EditCategory calls raker.v1.RakerServer.EditCategory.
func (c *rakerServerClient) EditCategory(ctx context.Context, req *v1.EditCategoryRequest) (*emptypb.Empty, error) {
	response, err := c.editCategory.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ScrapeInstagram calls raker.v1.RakerServer.ScrapeInstagram.
func (c *rakerServerClient) ScrapeInstagram(ctx context.Context, req *v1.UnaryScrapeRequest) (*v1.ScrapeResponse, error) {
	response, err := c.scrapeInstagram.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ScrapeHighlight calls raker.v1.RakerServer.ScrapeHighlight.
func (c *rakerServerClient) ScrapeHighlight(ctx context.Context, req *v1.UnaryScrapeRequest) (*v1.ScrapeResponse, error) {
	response, err := c.scrapeHighlight.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ScrapeStory calls raker.v1.RakerServer.ScrapeStory.
func (c *rakerServerClient) ScrapeStory(ctx context.Context, req *v1.UnaryScrapeRequest) (*v1.ScrapeResponse, error) {
	response, err := c.scrapeStory.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ScrapeTikTok calls raker.v1.RakerServer.ScrapeTikTok.
func (c *rakerServerClient) ScrapeTikTok(ctx context.Context, req *v1.BinaryScrapeRequest) (*v1.ScrapeResponse, error) {
	response, err := c.scrapeTikTok.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ScrapeSnapchat calls raker.v1.RakerServer.ScrapeSnapchat.
func (c *rakerServerClient) ScrapeSnapchat(ctx context.Context, req *v1.UnaryScrapeRequest) (*v1.ScrapeResponse, error) {
	response, err := c.scrapeSnapchat.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// ScrapeVSCO calls raker.v1.RakerServer.ScrapeVSCO.
func (c *rakerServerClient) ScrapeVSCO(ctx context.Context, req *v1.BinaryScrapeRequest) (*v1.ScrapeResponse, error) {
	response, err := c.scrapeVSCO.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// RemoveFile calls raker.v1.RakerServer.RemoveFile.
func (c *rakerServerClient) RemoveFile(ctx context.Context, req *v1.RemoveFileRequest) (*v1.ScrapeResponse, error) {
	response, err := c.removeFile.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// UpdateCategories calls raker.v1.RakerServer.UpdateCategories.
func (c *rakerServerClient) UpdateCategories(ctx context.Context, req *v1.UpdateCategoriesRequest) (*v1.ScrapeResponse, error) {
	response, err := c.updateCategories.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SearchHistory calls raker.v1.RakerServer.SearchHistory.
func (c *rakerServerClient) SearchHistory(ctx context.Context, req *v1.HistoryRequest) (*v1.HistoryResponse, error) {
	response, err := c.searchHistory.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// SearchHistoryOwners calls raker.v1.RakerServer.SearchHistoryOwners.
func (c *rakerServerClient) SearchHistoryOwners(ctx context.Context, req *v1.HistoryRequest) (*v1.HistoryOwnersResponse, error) {
	response, err := c.searchHistoryOwners.CallUnary(ctx, connect.NewRequest(req))
	if response != nil {
		return response.Msg, err
	}
	return nil, err
}

// RakerServerHandler is an implementation of the raker.v1.RakerServer service.
type RakerServerHandler interface {
	SignUpInstagram(context.Context, *v1.SignUpRequest) (*emptypb.Empty, error)
	SignInInstagram(context.Context, *v1.SignUpRequest) (*emptypb.Empty, error)
	EditCategory(context.Context, *v1.EditCategoryRequest) (*emptypb.Empty, error)
	ScrapeInstagram(context.Context, *v1.UnaryScrapeRequest) (*v1.ScrapeResponse, error)
	ScrapeHighlight(context.Context, *v1.UnaryScrapeRequest) (*v1.ScrapeResponse, error)
	ScrapeStory(context.Context, *v1.UnaryScrapeRequest) (*v1.ScrapeResponse, error)
	ScrapeTikTok(context.Context, *v1.BinaryScrapeRequest) (*v1.ScrapeResponse, error)
	ScrapeSnapchat(context.Context, *v1.UnaryScrapeRequest) (*v1.ScrapeResponse, error)
	ScrapeVSCO(context.Context, *v1.BinaryScrapeRequest) (*v1.ScrapeResponse, error)
	RemoveFile(context.Context, *v1.RemoveFileRequest) (*v1.ScrapeResponse, error)
	UpdateCategories(context.Context, *v1.UpdateCategoriesRequest) (*v1.ScrapeResponse, error)
	SearchHistory(context.Context, *v1.HistoryRequest) (*v1.HistoryResponse, error)
	SearchHistoryOwners(context.Context, *v1.HistoryRequest) (*v1.HistoryOwnersResponse, error)
}

// NewRakerServerHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRakerServerHandler(svc RakerServerHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	rakerServerMethods := v1.File_raker_v1_raker_proto.Services().ByName("RakerServer").Methods()
	rakerServerSignUpInstagramHandler := connect.NewUnaryHandlerSimple(
		RakerServerSignUpInstagramProcedure,
		svc.SignUpInstagram,
		connect.WithSchema(rakerServerMethods.ByName("SignUpInstagram")),
		connect.WithHandlerOptions(opts...),
	)
	rakerServerSignInInstagramHandler := connect.NewUnaryHandlerSimple(
		RakerServerSignInInstagramProcedure,
		svc.SignInInstagram,
		connect.WithSchema(rakerServerMethods.ByName("SignInInstagram")),
		connect.WithHandlerOptions(opts...),
	)
	rakerServerEditCategoryHandler := connect.NewUnaryHandlerSimple(
		RakerServerEditCategoryProcedure,
		svc.EditCategory,
		connect.WithSchema(rakerServerMethods.ByName("EditCategory")),
		connect.WithHandlerOptions(opts...),
	)
	rakerServerScrapeInstagramHandler := connect.NewUnaryHandlerSimple(
		RakerServerScrapeInstagramProcedure,
		svc.ScrapeInstagram,
		connect.WithSchema(rakerServerMethods.ByName("ScrapeInstagram")),
		connect.WithHandlerOptions(opts...),
	)
	rakerServerScrapeHighlightHandler := connect.NewUnaryHandlerSimple(
		RakerServerScrapeHighlightProcedure,
		svc.ScrapeHighlight,
		connect.WithSchema(rakerServerMethods.ByName("ScrapeHighlight")),
		connect.WithHandlerOptions(opts...),
	)
	rakerServerScrapeStoryHandler := connect.NewUnaryHandlerSimple(
		RakerServerScrapeStoryProcedure,
		svc.ScrapeStory,
		connect.WithSchema(rakerServerMethods.ByName("ScrapeStory")),
		connect.WithHandlerOptions(opts...),
	)
	rakerServerScrapeTikTokHandler := connect.NewUnaryHandlerSimple(
		RakerServerScrapeTikTokProcedure,
		svc.ScrapeTikTok,
		connect.WithSchema(rakerServerMethods.ByName("ScrapeTikTok")),
		connect.WithHandlerOptions(opts...),
	)
	rakerServerScrapeSnapchatHandler := connect.NewUnaryHandlerSimple(
		RakerServerScrapeSnapchatProcedure,
		svc.ScrapeSnapchat,
		connect.WithSchema(rakerServerMethods.ByName("ScrapeSnapchat")),
		connect.WithHandlerOptions(opts...),
	)
	rakerServerScrapeVSCOHandler := connect.NewUnaryHandlerSimple(
		RakerServerScrapeVSCOProcedure,
		svc.ScrapeVSCO,
		connect.WithSchema(rakerServerMethods.ByName("ScrapeVSCO")),
		connect.WithHandlerOptions(opts...),
	)
	rakerServerRemoveFileHandler := connect.NewUnaryHandlerSimple(
		RakerServerRemoveFileProcedure,
		svc.RemoveFile,
		connect.WithSchema(rakerServerMethods.ByName("RemoveFile")),
		connect.WithHandlerOptions(opts...),
	)
	rakerServerUpdateCategoriesHandler := connect.NewUnaryHandlerSimple(
		RakerServerUpdateCategoriesProcedure,
		svc.UpdateCategories,
		connect.WithSchema(rakerServerMethods.ByName("UpdateCategories")),
		connect.WithHandlerOptions(opts...),
	)
	rakerServerSearchHistoryHandler := connect.NewUnaryHandlerSimple(
		RakerServerSearchHistoryProcedure,
		svc.SearchHistory,
		connect.WithSchema(rakerServerMethods.ByName("SearchHistory")),
		connect.WithHandlerOptions(opts...),
	)
	rakerServerSearchHistoryOwnersHandler := connect.NewUnaryHandlerSimple(
		RakerServerSearchHistoryOwnersProcedure,
		svc.SearchHistoryOwners,
		connect.WithSchema(rakerServerMethods.ByName("SearchHistoryOwners")),
		connect.WithHandlerOptions(opts...),
	)
	return "/raker.v1.RakerServer/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RakerServerSignUpInstagramProcedure:
			rakerServerSignUpInstagramHandler.ServeHTTP(w, r)
		case RakerServerSignInInstagramProcedure:
			rakerServerSignInInstagramHandler.ServeHTTP(w, r)
		case RakerServerEditCategoryProcedure:
			rakerServerEditCategoryHandler.ServeHTTP(w, r)
		case RakerServerScrapeInstagramProcedure:
			rakerServerScrapeInstagramHandler.ServeHTTP(w, r)
		case RakerServerScrapeHighlightProcedure:
			rakerServerScrapeHighlightHandler.ServeHTTP(w, r)
		case RakerServerScrapeStoryProcedure:
			rakerServerScrapeStoryHandler.ServeHTTP(w, r)
		case RakerServerScrapeTikTokProcedure:
			rakerServerScrapeTikTokHandler.ServeHTTP(w, r)
		case RakerServerScrapeSnapchatProcedure:
			rakerServerScrapeSnapchatHandler.ServeHTTP(w, r)
		case RakerServerScrapeVSCOProcedure:
			rakerServerScrapeVSCOHandler.ServeHTTP(w, r)
		case RakerServerRemoveFileProcedure:
			rakerServerRemoveFileHandler.ServeHTTP(w, r)
		case RakerServerUpdateCategoriesProcedure:
			rakerServerUpdateCategoriesHandler.ServeHTTP(w, r)
		case RakerServerSearchHistoryProcedure:
			rakerServerSearchHistoryHandler.ServeHTTP(w, r)
		case RakerServerSearchHistoryOwnersProcedure:
			rakerServerSearchHistoryOwnersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRakerServerHandler returns CodeUnimplemented from all methods.
type UnimplementedRakerServerHandler struct{}

func (UnimplementedRakerServerHandler) SignUpInstagram(context.Context, *v1.SignUpRequest) (*emptypb.Empty, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("raker.v1.RakerServer.SignUpInstagram is not implemented"))
}

func (UnimplementedRakerServerHandler) SignInInstagram(context.Context, *v1.SignUpRequest) (*emptypb.Empty, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("raker.v1.RakerServer.SignInInstagram is not implemented"))
}

func (UnimplementedRakerServerHandler) EditCategory(context.Context, *v1.EditCategoryRequest) (*emptypb.Empty, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("raker.v1.RakerServer.EditCategory is not implemented"))
}

func (UnimplementedRakerServerHandler) ScrapeInstagram(context.Context, *v1.UnaryScrapeRequest) (*v1.ScrapeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("raker.v1.RakerServer.ScrapeInstagram is not implemented"))
}

func (UnimplementedRakerServerHandler) ScrapeHighlight(context.Context, *v1.UnaryScrapeRequest) (*v1.ScrapeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("raker.v1.RakerServer.ScrapeHighlight is not implemented"))
}

func (UnimplementedRakerServerHandler) ScrapeStory(context.Context, *v1.UnaryScrapeRequest) (*v1.ScrapeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("raker.v1.RakerServer.ScrapeStory is not implemented"))
}

func (UnimplementedRakerServerHandler) ScrapeTikTok(context.Context, *v1.BinaryScrapeRequest) (*v1.ScrapeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("raker.v1.RakerServer.ScrapeTikTok is not implemented"))
}

func (UnimplementedRakerServerHandler) ScrapeSnapchat(context.Context, *v1.UnaryScrapeRequest) (*v1.ScrapeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("raker.v1.RakerServer.ScrapeSnapchat is not implemented"))
}

func (UnimplementedRakerServerHandler) ScrapeVSCO(context.Context, *v1.BinaryScrapeRequest) (*v1.ScrapeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("raker.v1.RakerServer.ScrapeVSCO is not implemented"))
}

func (UnimplementedRakerServerHandler) RemoveFile(context.Context, *v1.RemoveFileRequest) (*v1.ScrapeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("raker.v1.RakerServer.RemoveFile is not implemented"))
}

func (UnimplementedRakerServerHandler) UpdateCategories(context.Context, *v1.UpdateCategoriesRequest) (*v1.ScrapeResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("raker.v1.RakerServer.UpdateCategories is not implemented"))
}

func (UnimplementedRakerServerHandler) SearchHistory(context.Context, *v1.HistoryRequest) (*v1.HistoryResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("raker.v1.RakerServer.SearchHistory is not implemented"))
}

func (UnimplementedRakerServerHandler) SearchHistoryOwners(context.Context, *v1.HistoryRequest) (*v1.HistoryOwnersResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("raker.v1.RakerServer.SearchHistoryOwners is not implemented"))
}
