// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: raker/v1/webauthn/passkey.proto

// buf:lint:ignore PACKAGE_VERSION_SUFFIX

package webauthn

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeginSignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginSignUpRequest) Reset() {
	*x = BeginSignUpRequest{}
	mi := &file_raker_v1_webauthn_passkey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginSignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginSignUpRequest) ProtoMessage() {}

func (x *BeginSignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_webauthn_passkey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginSignUpRequest.ProtoReflect.Descriptor instead.
func (*BeginSignUpRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_webauthn_passkey_proto_rawDescGZIP(), []int{0}
}

func (x *BeginSignUpRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type BeginSignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OptionsJson   string                 `protobuf:"bytes,2,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginSignUpResponse) Reset() {
	*x = BeginSignUpResponse{}
	mi := &file_raker_v1_webauthn_passkey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginSignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginSignUpResponse) ProtoMessage() {}

func (x *BeginSignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_webauthn_passkey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginSignUpResponse.ProtoReflect.Descriptor instead.
func (*BeginSignUpResponse) Descriptor() ([]byte, []int) {
	return file_raker_v1_webauthn_passkey_proto_rawDescGZIP(), []int{1}
}

func (x *BeginSignUpResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BeginSignUpResponse) GetOptionsJson() string {
	if x != nil {
		return x.OptionsJson
	}
	return ""
}

type FinishSignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PasskeyName   string                 `protobuf:"bytes,2,opt,name=passkey_name,json=passkeyName,proto3" json:"passkey_name,omitempty"`
	ResponseJson  string                 `protobuf:"bytes,3,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishSignUpRequest) Reset() {
	*x = FinishSignUpRequest{}
	mi := &file_raker_v1_webauthn_passkey_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishSignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishSignUpRequest) ProtoMessage() {}

func (x *FinishSignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_webauthn_passkey_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishSignUpRequest.ProtoReflect.Descriptor instead.
func (*FinishSignUpRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_webauthn_passkey_proto_rawDescGZIP(), []int{2}
}

func (x *FinishSignUpRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FinishSignUpRequest) GetPasskeyName() string {
	if x != nil {
		return x.PasskeyName
	}
	return ""
}

func (x *FinishSignUpRequest) GetResponseJson() string {
	if x != nil {
		return x.ResponseJson
	}
	return ""
}

type FinishSignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishSignUpResponse) Reset() {
	*x = FinishSignUpResponse{}
	mi := &file_raker_v1_webauthn_passkey_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishSignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishSignUpResponse) ProtoMessage() {}

func (x *FinishSignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_webauthn_passkey_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishSignUpResponse.ProtoReflect.Descriptor instead.
func (*FinishSignUpResponse) Descriptor() ([]byte, []int) {
	return file_raker_v1_webauthn_passkey_proto_rawDescGZIP(), []int{3}
}

func (x *FinishSignUpResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BeginSignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginSignInRequest) Reset() {
	*x = BeginSignInRequest{}
	mi := &file_raker_v1_webauthn_passkey_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginSignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginSignInRequest) ProtoMessage() {}

func (x *BeginSignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_webauthn_passkey_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginSignInRequest.ProtoReflect.Descriptor instead.
func (*BeginSignInRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_webauthn_passkey_proto_rawDescGZIP(), []int{4}
}

func (x *BeginSignInRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type BeginSignInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OptionsJson   string                 `protobuf:"bytes,2,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginSignInResponse) Reset() {
	*x = BeginSignInResponse{}
	mi := &file_raker_v1_webauthn_passkey_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginSignInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginSignInResponse) ProtoMessage() {}

func (x *BeginSignInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_webauthn_passkey_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginSignInResponse.ProtoReflect.Descriptor instead.
func (*BeginSignInResponse) Descriptor() ([]byte, []int) {
	return file_raker_v1_webauthn_passkey_proto_rawDescGZIP(), []int{5}
}

func (x *BeginSignInResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BeginSignInResponse) GetOptionsJson() string {
	if x != nil {
		return x.OptionsJson
	}
	return ""
}

type FinishSignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ResponseJson  string                 `protobuf:"bytes,2,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishSignInRequest) Reset() {
	*x = FinishSignInRequest{}
	mi := &file_raker_v1_webauthn_passkey_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishSignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishSignInRequest) ProtoMessage() {}

func (x *FinishSignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_webauthn_passkey_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishSignInRequest.ProtoReflect.Descriptor instead.
func (*FinishSignInRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_webauthn_passkey_proto_rawDescGZIP(), []int{6}
}

func (x *FinishSignInRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FinishSignInRequest) GetResponseJson() string {
	if x != nil {
		return x.ResponseJson
	}
	return ""
}

type FinishSignInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishSignInResponse) Reset() {
	*x = FinishSignInResponse{}
	mi := &file_raker_v1_webauthn_passkey_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishSignInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishSignInResponse) ProtoMessage() {}

func (x *FinishSignInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_webauthn_passkey_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishSignInResponse.ProtoReflect.Descriptor instead.
func (*FinishSignInResponse) Descriptor() ([]byte, []int) {
	return file_raker_v1_webauthn_passkey_proto_rawDescGZIP(), []int{7}
}

func (x *FinishSignInResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FinishSignInResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_raker_v1_webauthn_passkey_proto protoreflect.FileDescriptor

const file_raker_v1_webauthn_passkey_proto_rawDesc = "" +
	"\n" +
	"\x1fraker/v1/webauthn/passkey.proto\x12\x11raker.v1.webauthn\"0\n" +
	"\x12BeginSignUpRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"W\n" +
	"\x13BeginSignUpResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\foptions_json\x18\x02 \x01(\tR\voptionsJson\"|\n" +
	"\x13FinishSignUpRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fpasskey_name\x18\x02 \x01(\tR\vpasskeyName\x12#\n" +
	"\rresponse_json\x18\x03 \x01(\tR\fresponseJson\"0\n" +
	"\x14FinishSignUpResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"-\n" +
	"\x12BeginSignInRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"W\n" +
	"\x13BeginSignInResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\foptions_json\x18\x02 \x01(\tR\voptionsJson\"Y\n" +
	"\x13FinishSignInRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rresponse_json\x18\x02 \x01(\tR\fresponseJson\"I\n" +
	"\x14FinishSignInResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userIdB\xcd\x01\n" +
	"\x15com.raker.v1.webauthnB\fPasskeyProtoP\x01Z@github.com/AppleGamer22/raker/server/buf/proto/raker/v1/webauthn\xa2\x02\x03RVW\xaa\x02\x11Raker.V1.Webauthn\xca\x02\x11Raker\\V1\\Webauthn\xe2\x02\x1dRaker\\V1\\Webauthn\\GPBMetadata\xea\x02\x13Raker::V1::Webauthnb\x06proto3"

var (
	file_raker_v1_webauthn_passkey_proto_rawDescOnce sync.Once
	file_raker_v1_webauthn_passkey_proto_rawDescData []byte
)

func file_raker_v1_webauthn_passkey_proto_rawDescGZIP() []byte {
	file_raker_v1_webauthn_passkey_proto_rawDescOnce.Do(func() {
		file_raker_v1_webauthn_passkey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raker_v1_webauthn_passkey_proto_rawDesc), len(file_raker_v1_webauthn_passkey_proto_rawDesc)))
	})
	return file_raker_v1_webauthn_passkey_proto_rawDescData
}

var file_raker_v1_webauthn_passkey_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_raker_v1_webauthn_passkey_proto_goTypes = []any{
	(*BeginSignUpRequest)(nil),   // 0: raker.v1.webauthn.BeginSignUpRequest
	(*BeginSignUpResponse)(nil),  // 1: raker.v1.webauthn.BeginSignUpResponse
	(*FinishSignUpRequest)(nil),  // 2: raker.v1.webauthn.FinishSignUpRequest
	(*FinishSignUpResponse)(nil), // 3: raker.v1.webauthn.FinishSignUpResponse
	(*BeginSignInRequest)(nil),   // 4: raker.v1.webauthn.BeginSignInRequest
	(*BeginSignInResponse)(nil),  // 5: raker.v1.webauthn.BeginSignInResponse
	(*FinishSignInRequest)(nil),  // 6: raker.v1.webauthn.FinishSignInRequest
	(*FinishSignInResponse)(nil), // 7: raker.v1.webauthn.FinishSignInResponse
}
var file_raker_v1_webauthn_passkey_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_raker_v1_webauthn_passkey_proto_init() }
func file_raker_v1_webauthn_passkey_proto_init() {
	if File_raker_v1_webauthn_passkey_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raker_v1_webauthn_passkey_proto_rawDesc), len(file_raker_v1_webauthn_passkey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_raker_v1_webauthn_passkey_proto_goTypes,
		DependencyIndexes: file_raker_v1_webauthn_passkey_proto_depIdxs,
		MessageInfos:      file_raker_v1_webauthn_passkey_proto_msgTypes,
	}.Build()
	File_raker_v1_webauthn_passkey_proto = out.File
	file_raker_v1_webauthn_passkey_proto_goTypes = nil
	file_raker_v1_webauthn_passkey_proto_depIdxs = nil
}
