// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file raker/v1/passkey/passkey.proto (package raker.v1.passkey, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_VERSION_SUFFIX

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file raker/v1/passkey/passkey.proto.
 */
export const file_raker_v1_passkey_passkey: GenFile = /*@__PURE__*/
  fileDesc("Ch5yYWtlci92MS9wYXNza2V5L3Bhc3NrZXkucHJvdG8SEHJha2VyLnYxLnBhc3NrZXkiJgoSQmVnaW5TaWduVXBSZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJIj8KE0JlZ2luU2lnblVwUmVzcG9uc2USEgoKc2Vzc2lvbl9pZBgBIAEoCRIUCgxvcHRpb25zX2pzb24YAiABKAkiVgoTRmluaXNoU2lnblVwUmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJEhQKDHBhc3NrZXlfbmFtZRgCIAEoCRIVCg1yZXNwb25zZV9qc29uGAMgASgJIiYKEkJlZ2luU2lnbkluUmVxdWVzdBIQCgh1c2VybmFtZRgBIAEoCSI/ChNCZWdpblNpZ25JblJlc3BvbnNlEhIKCnNlc3Npb25faWQYASABKAkSFAoMb3B0aW9uc19qc29uGAIgASgJIkAKE0ZpbmlzaFNpZ25JblJlcXVlc3QSEgoKc2Vzc2lvbl9pZBgBIAEoCRIVCg1yZXNwb25zZV9qc29uGAIgASgJIjwKFFJlbmFtZVBhc3NrZXlSZXF1ZXN0EhIKCnBhc3NrZXlfaWQYASABKAwSEAoIbmV3X25hbWUYAiABKAlCxwEKFGNvbS5yYWtlci52MS5wYXNza2V5QgxQYXNza2V5UHJvdG9QAVo/Z2l0aHViLmNvbS9BcHBsZUdhbWVyMjIvcmFrZXIvc2VydmVyL2J1Zi9wcm90by9yYWtlci92MS9wYXNza2V5ogIDUlZQqgIQUmFrZXIuVjEuUGFzc2tlecoCEFJha2VyXFYxXFBhc3NrZXniAhxSYWtlclxWMVxQYXNza2V5XEdQQk1ldGFkYXRh6gISUmFrZXI6OlYxOjpQYXNza2V5YgZwcm90bzM");

/**
 * @generated from message raker.v1.passkey.BeginSignUpRequest
 */
export type BeginSignUpRequest = Message<"raker.v1.passkey.BeginSignUpRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;
};

/**
 * Describes the message raker.v1.passkey.BeginSignUpRequest.
 * Use `create(BeginSignUpRequestSchema)` to create a new message.
 */
export const BeginSignUpRequestSchema: GenMessage<BeginSignUpRequest> = /*@__PURE__*/
  messageDesc(file_raker_v1_passkey_passkey, 0);

/**
 * @generated from message raker.v1.passkey.BeginSignUpResponse
 */
export type BeginSignUpResponse = Message<"raker.v1.passkey.BeginSignUpResponse"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string options_json = 2;
   */
  optionsJson: string;
};

/**
 * Describes the message raker.v1.passkey.BeginSignUpResponse.
 * Use `create(BeginSignUpResponseSchema)` to create a new message.
 */
export const BeginSignUpResponseSchema: GenMessage<BeginSignUpResponse> = /*@__PURE__*/
  messageDesc(file_raker_v1_passkey_passkey, 1);

/**
 * @generated from message raker.v1.passkey.FinishSignUpRequest
 */
export type FinishSignUpRequest = Message<"raker.v1.passkey.FinishSignUpRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string passkey_name = 2;
   */
  passkeyName: string;

  /**
   * @generated from field: string response_json = 3;
   */
  responseJson: string;
};

/**
 * Describes the message raker.v1.passkey.FinishSignUpRequest.
 * Use `create(FinishSignUpRequestSchema)` to create a new message.
 */
export const FinishSignUpRequestSchema: GenMessage<FinishSignUpRequest> = /*@__PURE__*/
  messageDesc(file_raker_v1_passkey_passkey, 2);

/**
 * @generated from message raker.v1.passkey.BeginSignInRequest
 */
export type BeginSignInRequest = Message<"raker.v1.passkey.BeginSignInRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;
};

/**
 * Describes the message raker.v1.passkey.BeginSignInRequest.
 * Use `create(BeginSignInRequestSchema)` to create a new message.
 */
export const BeginSignInRequestSchema: GenMessage<BeginSignInRequest> = /*@__PURE__*/
  messageDesc(file_raker_v1_passkey_passkey, 3);

/**
 * @generated from message raker.v1.passkey.BeginSignInResponse
 */
export type BeginSignInResponse = Message<"raker.v1.passkey.BeginSignInResponse"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string options_json = 2;
   */
  optionsJson: string;
};

/**
 * Describes the message raker.v1.passkey.BeginSignInResponse.
 * Use `create(BeginSignInResponseSchema)` to create a new message.
 */
export const BeginSignInResponseSchema: GenMessage<BeginSignInResponse> = /*@__PURE__*/
  messageDesc(file_raker_v1_passkey_passkey, 4);

/**
 * @generated from message raker.v1.passkey.FinishSignInRequest
 */
export type FinishSignInRequest = Message<"raker.v1.passkey.FinishSignInRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string response_json = 2;
   */
  responseJson: string;
};

/**
 * Describes the message raker.v1.passkey.FinishSignInRequest.
 * Use `create(FinishSignInRequestSchema)` to create a new message.
 */
export const FinishSignInRequestSchema: GenMessage<FinishSignInRequest> = /*@__PURE__*/
  messageDesc(file_raker_v1_passkey_passkey, 5);

/**
 * @generated from message raker.v1.passkey.RenamePasskeyRequest
 */
export type RenamePasskeyRequest = Message<"raker.v1.passkey.RenamePasskeyRequest"> & {
  /**
   * @generated from field: bytes passkey_id = 1;
   */
  passkeyId: Uint8Array;

  /**
   * @generated from field: string new_name = 2;
   */
  newName: string;
};

/**
 * Describes the message raker.v1.passkey.RenamePasskeyRequest.
 * Use `create(RenamePasskeyRequestSchema)` to create a new message.
 */
export const RenamePasskeyRequestSchema: GenMessage<RenamePasskeyRequest> = /*@__PURE__*/
  messageDesc(file_raker_v1_passkey_passkey, 6);

