// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: raker/v1/passkey/passkey.proto

// buf:lint:ignore PACKAGE_VERSION_SUFFIX

package passkey

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeginSignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginSignUpRequest) Reset() {
	*x = BeginSignUpRequest{}
	mi := &file_raker_v1_passkey_passkey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginSignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginSignUpRequest) ProtoMessage() {}

func (x *BeginSignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_passkey_passkey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginSignUpRequest.ProtoReflect.Descriptor instead.
func (*BeginSignUpRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_passkey_passkey_proto_rawDescGZIP(), []int{0}
}

func (x *BeginSignUpRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type BeginSignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OptionsJson   string                 `protobuf:"bytes,2,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginSignUpResponse) Reset() {
	*x = BeginSignUpResponse{}
	mi := &file_raker_v1_passkey_passkey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginSignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginSignUpResponse) ProtoMessage() {}

func (x *BeginSignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_passkey_passkey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginSignUpResponse.ProtoReflect.Descriptor instead.
func (*BeginSignUpResponse) Descriptor() ([]byte, []int) {
	return file_raker_v1_passkey_passkey_proto_rawDescGZIP(), []int{1}
}

func (x *BeginSignUpResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BeginSignUpResponse) GetOptionsJson() string {
	if x != nil {
		return x.OptionsJson
	}
	return ""
}

type FinishSignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PasskeyName   string                 `protobuf:"bytes,2,opt,name=passkey_name,json=passkeyName,proto3" json:"passkey_name,omitempty"`
	ResponseJson  string                 `protobuf:"bytes,3,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishSignUpRequest) Reset() {
	*x = FinishSignUpRequest{}
	mi := &file_raker_v1_passkey_passkey_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishSignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishSignUpRequest) ProtoMessage() {}

func (x *FinishSignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_passkey_passkey_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishSignUpRequest.ProtoReflect.Descriptor instead.
func (*FinishSignUpRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_passkey_passkey_proto_rawDescGZIP(), []int{2}
}

func (x *FinishSignUpRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FinishSignUpRequest) GetPasskeyName() string {
	if x != nil {
		return x.PasskeyName
	}
	return ""
}

func (x *FinishSignUpRequest) GetResponseJson() string {
	if x != nil {
		return x.ResponseJson
	}
	return ""
}

type BeginSignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginSignInRequest) Reset() {
	*x = BeginSignInRequest{}
	mi := &file_raker_v1_passkey_passkey_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginSignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginSignInRequest) ProtoMessage() {}

func (x *BeginSignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_passkey_passkey_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginSignInRequest.ProtoReflect.Descriptor instead.
func (*BeginSignInRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_passkey_passkey_proto_rawDescGZIP(), []int{3}
}

func (x *BeginSignInRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type BeginSignInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OptionsJson   string                 `protobuf:"bytes,2,opt,name=options_json,json=optionsJson,proto3" json:"options_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginSignInResponse) Reset() {
	*x = BeginSignInResponse{}
	mi := &file_raker_v1_passkey_passkey_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginSignInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginSignInResponse) ProtoMessage() {}

func (x *BeginSignInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_passkey_passkey_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginSignInResponse.ProtoReflect.Descriptor instead.
func (*BeginSignInResponse) Descriptor() ([]byte, []int) {
	return file_raker_v1_passkey_passkey_proto_rawDescGZIP(), []int{4}
}

func (x *BeginSignInResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BeginSignInResponse) GetOptionsJson() string {
	if x != nil {
		return x.OptionsJson
	}
	return ""
}

type FinishSignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ResponseJson  string                 `protobuf:"bytes,2,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishSignInRequest) Reset() {
	*x = FinishSignInRequest{}
	mi := &file_raker_v1_passkey_passkey_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishSignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishSignInRequest) ProtoMessage() {}

func (x *FinishSignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_passkey_passkey_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishSignInRequest.ProtoReflect.Descriptor instead.
func (*FinishSignInRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_passkey_passkey_proto_rawDescGZIP(), []int{5}
}

func (x *FinishSignInRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FinishSignInRequest) GetResponseJson() string {
	if x != nil {
		return x.ResponseJson
	}
	return ""
}

type Passkey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Aaguid        []byte                 `protobuf:"bytes,3,opt,name=aaguid,proto3" json:"aaguid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Passkey) Reset() {
	*x = Passkey{}
	mi := &file_raker_v1_passkey_passkey_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Passkey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Passkey) ProtoMessage() {}

func (x *Passkey) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_passkey_passkey_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Passkey.ProtoReflect.Descriptor instead.
func (*Passkey) Descriptor() ([]byte, []int) {
	return file_raker_v1_passkey_passkey_proto_rawDescGZIP(), []int{6}
}

func (x *Passkey) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Passkey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Passkey) GetAaguid() []byte {
	if x != nil {
		return x.Aaguid
	}
	return nil
}

type PasskeysSettingsDisplay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passkeys      []*Passkey             `protobuf:"bytes,1,rep,name=passkeys,proto3" json:"passkeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasskeysSettingsDisplay) Reset() {
	*x = PasskeysSettingsDisplay{}
	mi := &file_raker_v1_passkey_passkey_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasskeysSettingsDisplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasskeysSettingsDisplay) ProtoMessage() {}

func (x *PasskeysSettingsDisplay) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_passkey_passkey_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasskeysSettingsDisplay.ProtoReflect.Descriptor instead.
func (*PasskeysSettingsDisplay) Descriptor() ([]byte, []int) {
	return file_raker_v1_passkey_passkey_proto_rawDescGZIP(), []int{7}
}

func (x *PasskeysSettingsDisplay) GetPasskeys() []*Passkey {
	if x != nil {
		return x.Passkeys
	}
	return nil
}

var File_raker_v1_passkey_passkey_proto protoreflect.FileDescriptor

const file_raker_v1_passkey_passkey_proto_rawDesc = "" +
	"\n" +
	"\x1eraker/v1/passkey/passkey.proto\x12\x10raker.v1.passkey\"0\n" +
	"\x12BeginSignUpRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"W\n" +
	"\x13BeginSignUpResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\foptions_json\x18\x02 \x01(\tR\voptionsJson\"|\n" +
	"\x13FinishSignUpRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fpasskey_name\x18\x02 \x01(\tR\vpasskeyName\x12#\n" +
	"\rresponse_json\x18\x03 \x01(\tR\fresponseJson\"0\n" +
	"\x12BeginSignInRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"W\n" +
	"\x13BeginSignInResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\foptions_json\x18\x02 \x01(\tR\voptionsJson\"Y\n" +
	"\x13FinishSignInRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rresponse_json\x18\x02 \x01(\tR\fresponseJson\"E\n" +
	"\aPasskey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06aaguid\x18\x03 \x01(\fR\x06aaguid\"P\n" +
	"\x17PasskeysSettingsDisplay\x125\n" +
	"\bpasskeys\x18\x01 \x03(\v2\x19.raker.v1.passkey.PasskeyR\bpasskeysB\xc7\x01\n" +
	"\x14com.raker.v1.passkeyB\fPasskeyProtoP\x01Z?github.com/AppleGamer22/raker/server/buf/proto/raker/v1/passkey\xa2\x02\x03RVP\xaa\x02\x10Raker.V1.Passkey\xca\x02\x10Raker\\V1\\Passkey\xe2\x02\x1cRaker\\V1\\Passkey\\GPBMetadata\xea\x02\x12Raker::V1::Passkeyb\x06proto3"

var (
	file_raker_v1_passkey_passkey_proto_rawDescOnce sync.Once
	file_raker_v1_passkey_passkey_proto_rawDescData []byte
)

func file_raker_v1_passkey_passkey_proto_rawDescGZIP() []byte {
	file_raker_v1_passkey_passkey_proto_rawDescOnce.Do(func() {
		file_raker_v1_passkey_passkey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raker_v1_passkey_passkey_proto_rawDesc), len(file_raker_v1_passkey_passkey_proto_rawDesc)))
	})
	return file_raker_v1_passkey_passkey_proto_rawDescData
}

var file_raker_v1_passkey_passkey_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_raker_v1_passkey_passkey_proto_goTypes = []any{
	(*BeginSignUpRequest)(nil),      // 0: raker.v1.passkey.BeginSignUpRequest
	(*BeginSignUpResponse)(nil),     // 1: raker.v1.passkey.BeginSignUpResponse
	(*FinishSignUpRequest)(nil),     // 2: raker.v1.passkey.FinishSignUpRequest
	(*BeginSignInRequest)(nil),      // 3: raker.v1.passkey.BeginSignInRequest
	(*BeginSignInResponse)(nil),     // 4: raker.v1.passkey.BeginSignInResponse
	(*FinishSignInRequest)(nil),     // 5: raker.v1.passkey.FinishSignInRequest
	(*Passkey)(nil),                 // 6: raker.v1.passkey.Passkey
	(*PasskeysSettingsDisplay)(nil), // 7: raker.v1.passkey.PasskeysSettingsDisplay
}
var file_raker_v1_passkey_passkey_proto_depIdxs = []int32{
	6, // 0: raker.v1.passkey.PasskeysSettingsDisplay.passkeys:type_name -> raker.v1.passkey.Passkey
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_raker_v1_passkey_passkey_proto_init() }
func file_raker_v1_passkey_passkey_proto_init() {
	if File_raker_v1_passkey_passkey_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raker_v1_passkey_passkey_proto_rawDesc), len(file_raker_v1_passkey_passkey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_raker_v1_passkey_passkey_proto_goTypes,
		DependencyIndexes: file_raker_v1_passkey_passkey_proto_depIdxs,
		MessageInfos:      file_raker_v1_passkey_passkey_proto_msgTypes,
	}.Build()
	File_raker_v1_passkey_passkey_proto = out.File
	file_raker_v1_passkey_passkey_proto_goTypes = nil
	file_raker_v1_passkey_passkey_proto_depIdxs = nil
}
