// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: raker/v1/raker.proto

package v1

import (
	latlng "google.golang.org/genproto/googleapis/type/latlng"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostType int32

const (
	PostType_Instagram PostType = 0
	PostType_Highlight PostType = 1
	PostType_Story     PostType = 2
	PostType_TikTok    PostType = 3
	PostType_Snapchat  PostType = 4
	PostType_VSCO      PostType = 5
)

// Enum value maps for PostType.
var (
	PostType_name = map[int32]string{
		0: "Instagram",
		1: "Highlight",
		2: "Story",
		3: "TikTok",
		4: "Snapchat",
		5: "VSCO",
	}
	PostType_value = map[string]int32{
		"Instagram": 0,
		"Highlight": 1,
		"Story":     2,
		"TikTok":    3,
		"Snapchat":  4,
		"VSCO":      5,
	}
)

func (x PostType) Enum() *PostType {
	p := new(PostType)
	*p = x
	return p
}

func (x PostType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostType) Descriptor() protoreflect.EnumDescriptor {
	return file_raker_v1_raker_proto_enumTypes[0].Descriptor()
}

func (PostType) Type() protoreflect.EnumType {
	return &file_raker_v1_raker_proto_enumTypes[0]
}

func (x PostType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostType.Descriptor instead.
func (PostType) EnumDescriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{0}
}

type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	SessionId     *string                `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	UserId        *string                `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_raker_v1_raker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{0}
}

func (x *SignUpRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignUpRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SignUpRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type SignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequest) Reset() {
	*x = SignInRequest{}
	mi := &file_raker_v1_raker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequest) ProtoMessage() {}

func (x *SignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequest.ProtoReflect.Descriptor instead.
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{1}
}

func (x *SignInRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []string               `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCategoriesResponse) Reset() {
	*x = UserCategoriesResponse{}
	mi := &file_raker_v1_raker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCategoriesResponse) ProtoMessage() {}

func (x *UserCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCategoriesResponse.ProtoReflect.Descriptor instead.
func (*UserCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{2}
}

func (x *UserCategoriesResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type EditCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldCategory   string                 `protobuf:"bytes,1,opt,name=old_category,json=oldCategory,proto3" json:"old_category,omitempty"`
	NewCategory   string                 `protobuf:"bytes,2,opt,name=new_category,json=newCategory,proto3" json:"new_category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCategoryRequest) Reset() {
	*x = EditCategoryRequest{}
	mi := &file_raker_v1_raker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCategoryRequest) ProtoMessage() {}

func (x *EditCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCategoryRequest.ProtoReflect.Descriptor instead.
func (*EditCategoryRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{3}
}

func (x *EditCategoryRequest) GetOldCategory() string {
	if x != nil {
		return x.OldCategory
	}
	return ""
}

func (x *EditCategoryRequest) GetNewCategory() string {
	if x != nil {
		return x.NewCategory
	}
	return ""
}

type EditUserCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      *string                `protobuf:"bytes,1,opt,name=password,proto3,oneof" json:"password,omitempty"`
	SessionId     *string                `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	UserId        *string                `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditUserCredentialsRequest) Reset() {
	*x = EditUserCredentialsRequest{}
	mi := &file_raker_v1_raker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditUserCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditUserCredentialsRequest) ProtoMessage() {}

func (x *EditUserCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditUserCredentialsRequest.ProtoReflect.Descriptor instead.
func (*EditUserCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{4}
}

func (x *EditUserCredentialsRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *EditUserCredentialsRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *EditUserCredentialsRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type UnaryScrapeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          string                 `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	Incognito     *bool                  `protobuf:"varint,2,opt,name=incognito,proto3,oneof" json:"incognito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnaryScrapeRequest) Reset() {
	*x = UnaryScrapeRequest{}
	mi := &file_raker_v1_raker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnaryScrapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryScrapeRequest) ProtoMessage() {}

func (x *UnaryScrapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryScrapeRequest.ProtoReflect.Descriptor instead.
func (*UnaryScrapeRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{5}
}

func (x *UnaryScrapeRequest) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *UnaryScrapeRequest) GetIncognito() bool {
	if x != nil && x.Incognito != nil {
		return *x.Incognito
	}
	return false
}

type BinaryScrapeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Post          string                 `protobuf:"bytes,2,opt,name=post,proto3" json:"post,omitempty"`
	Incognito     *bool                  `protobuf:"varint,3,opt,name=incognito,proto3,oneof" json:"incognito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryScrapeRequest) Reset() {
	*x = BinaryScrapeRequest{}
	mi := &file_raker_v1_raker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryScrapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryScrapeRequest) ProtoMessage() {}

func (x *BinaryScrapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryScrapeRequest.ProtoReflect.Descriptor instead.
func (*BinaryScrapeRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{6}
}

func (x *BinaryScrapeRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *BinaryScrapeRequest) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *BinaryScrapeRequest) GetIncognito() bool {
	if x != nil && x.Incognito != nil {
		return *x.Incognito
	}
	return false
}

type ScrapeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostType      PostType               `protobuf:"varint,1,opt,name=post_type,json=postType,proto3,enum=raker.v1.PostType" json:"post_type,omitempty"`
	PostOwner     string                 `protobuf:"bytes,2,opt,name=post_owner,json=postOwner,proto3" json:"post_owner,omitempty"`
	Post          string                 `protobuf:"bytes,3,opt,name=post,proto3" json:"post,omitempty"`
	PostDate      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=post_date,json=postDate,proto3" json:"post_date,omitempty"`
	Files         []string               `protobuf:"bytes,5,rep,name=files,proto3" json:"files,omitempty"`
	Categories    []string               `protobuf:"bytes,6,rep,name=categories,proto3" json:"categories,omitempty"`
	Incognito     bool                   `protobuf:"varint,7,opt,name=incognito,proto3" json:"incognito,omitempty"`
	Coordinates   *latlng.LatLng         `protobuf:"bytes,8,opt,name=coordinates,proto3,oneof" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeResponse) Reset() {
	*x = ScrapeResponse{}
	mi := &file_raker_v1_raker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeResponse) ProtoMessage() {}

func (x *ScrapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeResponse.ProtoReflect.Descriptor instead.
func (*ScrapeResponse) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{7}
}

func (x *ScrapeResponse) GetPostType() PostType {
	if x != nil {
		return x.PostType
	}
	return PostType_Instagram
}

func (x *ScrapeResponse) GetPostOwner() string {
	if x != nil {
		return x.PostOwner
	}
	return ""
}

func (x *ScrapeResponse) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *ScrapeResponse) GetPostDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PostDate
	}
	return nil
}

func (x *ScrapeResponse) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ScrapeResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ScrapeResponse) GetIncognito() bool {
	if x != nil {
		return x.Incognito
	}
	return false
}

func (x *ScrapeResponse) GetCoordinates() *latlng.LatLng {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type RemoveFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PostType               `protobuf:"varint,1,opt,name=type,proto3,enum=raker.v1.PostType" json:"type,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Post          string                 `protobuf:"bytes,3,opt,name=post,proto3" json:"post,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFileRequest) Reset() {
	*x = RemoveFileRequest{}
	mi := &file_raker_v1_raker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileRequest) ProtoMessage() {}

func (x *RemoveFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileRequest.ProtoReflect.Descriptor instead.
func (*RemoveFileRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveFileRequest) GetType() PostType {
	if x != nil {
		return x.Type
	}
	return PostType_Instagram
}

func (x *RemoveFileRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RemoveFileRequest) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *RemoveFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type UpdateCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PostType               `protobuf:"varint,1,opt,name=type,proto3,enum=raker.v1.PostType" json:"type,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Post          string                 `protobuf:"bytes,3,opt,name=post,proto3" json:"post,omitempty"`
	Categories    []string               `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoriesRequest) Reset() {
	*x = UpdateCategoriesRequest{}
	mi := &file_raker_v1_raker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoriesRequest) ProtoMessage() {}

func (x *UpdateCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoriesRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCategoriesRequest) GetType() PostType {
	if x != nil {
		return x.Type
	}
	return PostType_Instagram
}

func (x *UpdateCategoriesRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *UpdateCategoriesRequest) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *UpdateCategoriesRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Exclusive     bool                   `protobuf:"varint,2,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Categories    []string               `protobuf:"bytes,5,rep,name=categories,proto3" json:"categories,omitempty"`
	Types         []PostType             `protobuf:"varint,6,rep,packed,name=types,proto3,enum=raker.v1.PostType" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_raker_v1_raker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{10}
}

func (x *HistoryRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *HistoryRequest) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

func (x *HistoryRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *HistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *HistoryRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *HistoryRequest) GetTypes() []PostType {
	if x != nil {
		return x.Types
	}
	return nil
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int64                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Histories     []*ScrapeResponse      `protobuf:"bytes,3,rep,name=histories,proto3" json:"histories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_raker_v1_raker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{11}
}

func (x *HistoryResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *HistoryResponse) GetHistories() []*ScrapeResponse {
	if x != nil {
		return x.Histories
	}
	return nil
}

type HistoryOwnersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owners        []string               `protobuf:"bytes,1,rep,name=owners,proto3" json:"owners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryOwnersResponse) Reset() {
	*x = HistoryOwnersResponse{}
	mi := &file_raker_v1_raker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryOwnersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryOwnersResponse) ProtoMessage() {}

func (x *HistoryOwnersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryOwnersResponse.ProtoReflect.Descriptor instead.
func (*HistoryOwnersResponse) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{12}
}

func (x *HistoryOwnersResponse) GetOwners() []string {
	if x != nil {
		return x.Owners
	}
	return nil
}

var File_raker_v1_raker_proto protoreflect.FileDescriptor

const file_raker_v1_raker_proto_rawDesc = "" +
	"\n" +
	"\x14raker/v1/raker.proto\x12\braker.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18google/type/latlng.proto\"\xa4\x01\n" +
	"\rSignUpRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\"\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tH\x00R\tsessionId\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x04 \x01(\tH\x01R\x06userId\x88\x01\x01B\r\n" +
	"\v_session_idB\n" +
	"\n" +
	"\b_user_id\"G\n" +
	"\rSignInRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"8\n" +
	"\x16UserCategoriesResponse\x12\x1e\n" +
	"\n" +
	"categories\x18\x01 \x03(\tR\n" +
	"categories\"[\n" +
	"\x13EditCategoryRequest\x12!\n" +
	"\fold_category\x18\x01 \x01(\tR\voldCategory\x12!\n" +
	"\fnew_category\x18\x02 \x01(\tR\vnewCategory\"\xa7\x01\n" +
	"\x1aEditUserCredentialsRequest\x12\x1f\n" +
	"\bpassword\x18\x01 \x01(\tH\x00R\bpassword\x88\x01\x01\x12\"\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tH\x01R\tsessionId\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x03 \x01(\tH\x02R\x06userId\x88\x01\x01B\v\n" +
	"\t_passwordB\r\n" +
	"\v_session_idB\n" +
	"\n" +
	"\b_user_id\"Y\n" +
	"\x12UnaryScrapeRequest\x12\x12\n" +
	"\x04post\x18\x01 \x01(\tR\x04post\x12!\n" +
	"\tincognito\x18\x02 \x01(\bH\x00R\tincognito\x88\x01\x01B\f\n" +
	"\n" +
	"_incognito\"p\n" +
	"\x13BinaryScrapeRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04post\x18\x02 \x01(\tR\x04post\x12!\n" +
	"\tincognito\x18\x03 \x01(\bH\x00R\tincognito\x88\x01\x01B\f\n" +
	"\n" +
	"_incognito\"\xcd\x02\n" +
	"\x0eScrapeResponse\x12/\n" +
	"\tpost_type\x18\x01 \x01(\x0e2\x12.raker.v1.PostTypeR\bpostType\x12\x1d\n" +
	"\n" +
	"post_owner\x18\x02 \x01(\tR\tpostOwner\x12\x12\n" +
	"\x04post\x18\x03 \x01(\tR\x04post\x127\n" +
	"\tpost_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bpostDate\x12\x14\n" +
	"\x05files\x18\x05 \x03(\tR\x05files\x12\x1e\n" +
	"\n" +
	"categories\x18\x06 \x03(\tR\n" +
	"categories\x12\x1c\n" +
	"\tincognito\x18\a \x01(\bR\tincognito\x12:\n" +
	"\vcoordinates\x18\b \x01(\v2\x13.google.type.LatLngH\x00R\vcoordinates\x88\x01\x01B\x0e\n" +
	"\f_coordinates\"y\n" +
	"\x11RemoveFileRequest\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.raker.v1.PostTypeR\x04type\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x12\n" +
	"\x04post\x18\x03 \x01(\tR\x04post\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"\x8b\x01\n" +
	"\x17UpdateCategoriesRequest\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.raker.v1.PostTypeR\x04type\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x12\n" +
	"\x04post\x18\x03 \x01(\tR\x04post\x12\x1e\n" +
	"\n" +
	"categories\x18\x04 \x03(\tR\n" +
	"categories\"\xbf\x01\n" +
	"\x0eHistoryRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x1c\n" +
	"\texclusive\x18\x02 \x01(\bR\texclusive\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1e\n" +
	"\n" +
	"categories\x18\x05 \x03(\tR\n" +
	"categories\x12(\n" +
	"\x05types\x18\x06 \x03(\x0e2\x12.raker.v1.PostTypeR\x05types\"j\n" +
	"\x0fHistoryResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x03R\n" +
	"totalCount\x126\n" +
	"\thistories\x18\x03 \x03(\v2\x18.raker.v1.ScrapeResponseR\thistories\"/\n" +
	"\x15HistoryOwnersResponse\x12\x16\n" +
	"\x06owners\x18\x01 \x03(\tR\x06owners*W\n" +
	"\bPostType\x12\r\n" +
	"\tInstagram\x10\x00\x12\r\n" +
	"\tHighlight\x10\x01\x12\t\n" +
	"\x05Story\x10\x02\x12\n" +
	"\n" +
	"\x06TikTok\x10\x03\x12\f\n" +
	"\bSnapchat\x10\x04\x12\b\n" +
	"\x04VSCO\x10\x052\xe5\b\n" +
	"\vRakerServer\x12B\n" +
	"\x0fSignUpInstagram\x12\x17.raker.v1.SignUpRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\x0fSignInInstagram\x12\x17.raker.v1.SignInRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\fEditCategory\x12\x1d.raker.v1.EditCategoryRequest\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\x13EditUserCredentials\x12$.raker.v1.EditUserCredentialsRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\x11GetUserCategories\x12\x16.google.protobuf.Empty\x1a .raker.v1.UserCategoriesResponse\x12I\n" +
	"\x0fScrapeInstagram\x12\x1c.raker.v1.UnaryScrapeRequest\x1a\x18.raker.v1.ScrapeResponse\x12I\n" +
	"\x0fScrapeHighlight\x12\x1c.raker.v1.UnaryScrapeRequest\x1a\x18.raker.v1.ScrapeResponse\x12E\n" +
	"\vScrapeStory\x12\x1c.raker.v1.UnaryScrapeRequest\x1a\x18.raker.v1.ScrapeResponse\x12G\n" +
	"\fScrapeTikTok\x12\x1d.raker.v1.BinaryScrapeRequest\x1a\x18.raker.v1.ScrapeResponse\x12H\n" +
	"\x0eScrapeSnapchat\x12\x1c.raker.v1.UnaryScrapeRequest\x1a\x18.raker.v1.ScrapeResponse\x12E\n" +
	"\n" +
	"ScrapeVSCO\x12\x1d.raker.v1.BinaryScrapeRequest\x1a\x18.raker.v1.ScrapeResponse\x12C\n" +
	"\n" +
	"RemoveFile\x12\x1b.raker.v1.RemoveFileRequest\x1a\x18.raker.v1.ScrapeResponse\x12O\n" +
	"\x10UpdateCategories\x12!.raker.v1.UpdateCategoriesRequest\x1a\x18.raker.v1.ScrapeResponse\x12D\n" +
	"\rSearchHistory\x12\x18.raker.v1.HistoryRequest\x1a\x19.raker.v1.HistoryResponse\x12P\n" +
	"\x13SearchHistoryOwners\x12\x18.raker.v1.HistoryRequest\x1a\x1f.raker.v1.HistoryOwnersResponseB\x94\x01\n" +
	"\fcom.raker.v1B\n" +
	"RakerProtoP\x01Z7github.com/AppleGamer22/raker/server/buf/proto/raker/v1\xa2\x02\x03RXX\xaa\x02\bRaker.V1\xca\x02\bRaker\\V1\xe2\x02\x14Raker\\V1\\GPBMetadata\xea\x02\tRaker::V1b\x06proto3"

var (
	file_raker_v1_raker_proto_rawDescOnce sync.Once
	file_raker_v1_raker_proto_rawDescData []byte
)

func file_raker_v1_raker_proto_rawDescGZIP() []byte {
	file_raker_v1_raker_proto_rawDescOnce.Do(func() {
		file_raker_v1_raker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raker_v1_raker_proto_rawDesc), len(file_raker_v1_raker_proto_rawDesc)))
	})
	return file_raker_v1_raker_proto_rawDescData
}

var file_raker_v1_raker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_raker_v1_raker_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_raker_v1_raker_proto_goTypes = []any{
	(PostType)(0),                      // 0: raker.v1.PostType
	(*SignUpRequest)(nil),              // 1: raker.v1.SignUpRequest
	(*SignInRequest)(nil),              // 2: raker.v1.SignInRequest
	(*UserCategoriesResponse)(nil),     // 3: raker.v1.UserCategoriesResponse
	(*EditCategoryRequest)(nil),        // 4: raker.v1.EditCategoryRequest
	(*EditUserCredentialsRequest)(nil), // 5: raker.v1.EditUserCredentialsRequest
	(*UnaryScrapeRequest)(nil),         // 6: raker.v1.UnaryScrapeRequest
	(*BinaryScrapeRequest)(nil),        // 7: raker.v1.BinaryScrapeRequest
	(*ScrapeResponse)(nil),             // 8: raker.v1.ScrapeResponse
	(*RemoveFileRequest)(nil),          // 9: raker.v1.RemoveFileRequest
	(*UpdateCategoriesRequest)(nil),    // 10: raker.v1.UpdateCategoriesRequest
	(*HistoryRequest)(nil),             // 11: raker.v1.HistoryRequest
	(*HistoryResponse)(nil),            // 12: raker.v1.HistoryResponse
	(*HistoryOwnersResponse)(nil),      // 13: raker.v1.HistoryOwnersResponse
	(*timestamppb.Timestamp)(nil),      // 14: google.protobuf.Timestamp
	(*latlng.LatLng)(nil),              // 15: google.type.LatLng
	(*emptypb.Empty)(nil),              // 16: google.protobuf.Empty
}
var file_raker_v1_raker_proto_depIdxs = []int32{
	0,  // 0: raker.v1.ScrapeResponse.post_type:type_name -> raker.v1.PostType
	14, // 1: raker.v1.ScrapeResponse.post_date:type_name -> google.protobuf.Timestamp
	15, // 2: raker.v1.ScrapeResponse.coordinates:type_name -> google.type.LatLng
	0,  // 3: raker.v1.RemoveFileRequest.type:type_name -> raker.v1.PostType
	0,  // 4: raker.v1.UpdateCategoriesRequest.type:type_name -> raker.v1.PostType
	0,  // 5: raker.v1.HistoryRequest.types:type_name -> raker.v1.PostType
	8,  // 6: raker.v1.HistoryResponse.histories:type_name -> raker.v1.ScrapeResponse
	1,  // 7: raker.v1.RakerServer.SignUpInstagram:input_type -> raker.v1.SignUpRequest
	2,  // 8: raker.v1.RakerServer.SignInInstagram:input_type -> raker.v1.SignInRequest
	4,  // 9: raker.v1.RakerServer.EditCategory:input_type -> raker.v1.EditCategoryRequest
	5,  // 10: raker.v1.RakerServer.EditUserCredentials:input_type -> raker.v1.EditUserCredentialsRequest
	16, // 11: raker.v1.RakerServer.GetUserCategories:input_type -> google.protobuf.Empty
	6,  // 12: raker.v1.RakerServer.ScrapeInstagram:input_type -> raker.v1.UnaryScrapeRequest
	6,  // 13: raker.v1.RakerServer.ScrapeHighlight:input_type -> raker.v1.UnaryScrapeRequest
	6,  // 14: raker.v1.RakerServer.ScrapeStory:input_type -> raker.v1.UnaryScrapeRequest
	7,  // 15: raker.v1.RakerServer.ScrapeTikTok:input_type -> raker.v1.BinaryScrapeRequest
	6,  // 16: raker.v1.RakerServer.ScrapeSnapchat:input_type -> raker.v1.UnaryScrapeRequest
	7,  // 17: raker.v1.RakerServer.ScrapeVSCO:input_type -> raker.v1.BinaryScrapeRequest
	9,  // 18: raker.v1.RakerServer.RemoveFile:input_type -> raker.v1.RemoveFileRequest
	10, // 19: raker.v1.RakerServer.UpdateCategories:input_type -> raker.v1.UpdateCategoriesRequest
	11, // 20: raker.v1.RakerServer.SearchHistory:input_type -> raker.v1.HistoryRequest
	11, // 21: raker.v1.RakerServer.SearchHistoryOwners:input_type -> raker.v1.HistoryRequest
	16, // 22: raker.v1.RakerServer.SignUpInstagram:output_type -> google.protobuf.Empty
	16, // 23: raker.v1.RakerServer.SignInInstagram:output_type -> google.protobuf.Empty
	16, // 24: raker.v1.RakerServer.EditCategory:output_type -> google.protobuf.Empty
	16, // 25: raker.v1.RakerServer.EditUserCredentials:output_type -> google.protobuf.Empty
	3,  // 26: raker.v1.RakerServer.GetUserCategories:output_type -> raker.v1.UserCategoriesResponse
	8,  // 27: raker.v1.RakerServer.ScrapeInstagram:output_type -> raker.v1.ScrapeResponse
	8,  // 28: raker.v1.RakerServer.ScrapeHighlight:output_type -> raker.v1.ScrapeResponse
	8,  // 29: raker.v1.RakerServer.ScrapeStory:output_type -> raker.v1.ScrapeResponse
	8,  // 30: raker.v1.RakerServer.ScrapeTikTok:output_type -> raker.v1.ScrapeResponse
	8,  // 31: raker.v1.RakerServer.ScrapeSnapchat:output_type -> raker.v1.ScrapeResponse
	8,  // 32: raker.v1.RakerServer.ScrapeVSCO:output_type -> raker.v1.ScrapeResponse
	8,  // 33: raker.v1.RakerServer.RemoveFile:output_type -> raker.v1.ScrapeResponse
	8,  // 34: raker.v1.RakerServer.UpdateCategories:output_type -> raker.v1.ScrapeResponse
	12, // 35: raker.v1.RakerServer.SearchHistory:output_type -> raker.v1.HistoryResponse
	13, // 36: raker.v1.RakerServer.SearchHistoryOwners:output_type -> raker.v1.HistoryOwnersResponse
	22, // [22:37] is the sub-list for method output_type
	7,  // [7:22] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_raker_v1_raker_proto_init() }
func file_raker_v1_raker_proto_init() {
	if File_raker_v1_raker_proto != nil {
		return
	}
	file_raker_v1_raker_proto_msgTypes[0].OneofWrappers = []any{}
	file_raker_v1_raker_proto_msgTypes[4].OneofWrappers = []any{}
	file_raker_v1_raker_proto_msgTypes[5].OneofWrappers = []any{}
	file_raker_v1_raker_proto_msgTypes[6].OneofWrappers = []any{}
	file_raker_v1_raker_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raker_v1_raker_proto_rawDesc), len(file_raker_v1_raker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raker_v1_raker_proto_goTypes,
		DependencyIndexes: file_raker_v1_raker_proto_depIdxs,
		EnumInfos:         file_raker_v1_raker_proto_enumTypes,
		MessageInfos:      file_raker_v1_raker_proto_msgTypes,
	}.Build()
	File_raker_v1_raker_proto = out.File
	file_raker_v1_raker_proto_goTypes = nil
	file_raker_v1_raker_proto_depIdxs = nil
}
