// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: raker/v1/raker.proto

package v1

import (
	datetime "google.golang.org/genproto/googleapis/type/datetime"
	latlng "google.golang.org/genproto/googleapis/type/latlng"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_Instagram MediaType = 0
	MediaType_Highlight MediaType = 1
	MediaType_Story     MediaType = 2
	MediaType_TikTok    MediaType = 3
	MediaType_VSCO      MediaType = 4
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "Instagram",
		1: "Highlight",
		2: "Story",
		3: "TikTok",
		4: "VSCO",
	}
	MediaType_value = map[string]int32{
		"Instagram": 0,
		"Highlight": 1,
		"Story":     2,
		"TikTok":    3,
		"VSCO":      4,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_raker_v1_raker_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_raker_v1_raker_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{0}
}

type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	SessionId     *string                `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	UserId        *string                `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_raker_v1_raker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{0}
}

func (x *SignUpRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignUpRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *SignUpRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type SignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequest) Reset() {
	*x = SignInRequest{}
	mi := &file_raker_v1_raker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequest) ProtoMessage() {}

func (x *SignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequest.ProtoReflect.Descriptor instead.
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{1}
}

func (x *SignInRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type EditCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldCategory   string                 `protobuf:"bytes,1,opt,name=old_category,json=oldCategory,proto3" json:"old_category,omitempty"`
	NewCategory   string                 `protobuf:"bytes,2,opt,name=new_category,json=newCategory,proto3" json:"new_category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditCategoryRequest) Reset() {
	*x = EditCategoryRequest{}
	mi := &file_raker_v1_raker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditCategoryRequest) ProtoMessage() {}

func (x *EditCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditCategoryRequest.ProtoReflect.Descriptor instead.
func (*EditCategoryRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{2}
}

func (x *EditCategoryRequest) GetOldCategory() string {
	if x != nil {
		return x.OldCategory
	}
	return ""
}

func (x *EditCategoryRequest) GetNewCategory() string {
	if x != nil {
		return x.NewCategory
	}
	return ""
}

type UnaryScrapeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          string                 `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	Incognito     *bool                  `protobuf:"varint,2,opt,name=incognito,proto3,oneof" json:"incognito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnaryScrapeRequest) Reset() {
	*x = UnaryScrapeRequest{}
	mi := &file_raker_v1_raker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnaryScrapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryScrapeRequest) ProtoMessage() {}

func (x *UnaryScrapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryScrapeRequest.ProtoReflect.Descriptor instead.
func (*UnaryScrapeRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{3}
}

func (x *UnaryScrapeRequest) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *UnaryScrapeRequest) GetIncognito() bool {
	if x != nil && x.Incognito != nil {
		return *x.Incognito
	}
	return false
}

type BinaryScrapeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Post          string                 `protobuf:"bytes,2,opt,name=post,proto3" json:"post,omitempty"`
	Incognito     *bool                  `protobuf:"varint,3,opt,name=incognito,proto3,oneof" json:"incognito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryScrapeRequest) Reset() {
	*x = BinaryScrapeRequest{}
	mi := &file_raker_v1_raker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryScrapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryScrapeRequest) ProtoMessage() {}

func (x *BinaryScrapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryScrapeRequest.ProtoReflect.Descriptor instead.
func (*BinaryScrapeRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{4}
}

func (x *BinaryScrapeRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *BinaryScrapeRequest) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *BinaryScrapeRequest) GetIncognito() bool {
	if x != nil && x.Incognito != nil {
		return *x.Incognito
	}
	return false
}

type ScrapeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PostType      MediaType              `protobuf:"varint,2,opt,name=post_type,json=postType,proto3,enum=raker.v1.MediaType" json:"post_type,omitempty"`
	PostOwner     string                 `protobuf:"bytes,3,opt,name=post_owner,json=postOwner,proto3" json:"post_owner,omitempty"`
	Post          string                 `protobuf:"bytes,4,opt,name=post,proto3" json:"post,omitempty"`
	PostDate      *datetime.DateTime     `protobuf:"bytes,5,opt,name=post_date,json=postDate,proto3" json:"post_date,omitempty"`
	Files         []string               `protobuf:"bytes,6,rep,name=files,proto3" json:"files,omitempty"`
	Categories    []string               `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	Incognito     bool                   `protobuf:"varint,8,opt,name=incognito,proto3" json:"incognito,omitempty"`
	Coordinates   *latlng.LatLng         `protobuf:"bytes,9,opt,name=coordinates,proto3,oneof" json:"coordinates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeResponse) Reset() {
	*x = ScrapeResponse{}
	mi := &file_raker_v1_raker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeResponse) ProtoMessage() {}

func (x *ScrapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeResponse.ProtoReflect.Descriptor instead.
func (*ScrapeResponse) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{5}
}

func (x *ScrapeResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ScrapeResponse) GetPostType() MediaType {
	if x != nil {
		return x.PostType
	}
	return MediaType_Instagram
}

func (x *ScrapeResponse) GetPostOwner() string {
	if x != nil {
		return x.PostOwner
	}
	return ""
}

func (x *ScrapeResponse) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *ScrapeResponse) GetPostDate() *datetime.DateTime {
	if x != nil {
		return x.PostDate
	}
	return nil
}

func (x *ScrapeResponse) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ScrapeResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ScrapeResponse) GetIncognito() bool {
	if x != nil {
		return x.Incognito
	}
	return false
}

func (x *ScrapeResponse) GetCoordinates() *latlng.LatLng {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type RemoveFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MediaType              `protobuf:"varint,1,opt,name=type,proto3,enum=raker.v1.MediaType" json:"type,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Post          string                 `protobuf:"bytes,3,opt,name=post,proto3" json:"post,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFileRequest) Reset() {
	*x = RemoveFileRequest{}
	mi := &file_raker_v1_raker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFileRequest) ProtoMessage() {}

func (x *RemoveFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFileRequest.ProtoReflect.Descriptor instead.
func (*RemoveFileRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveFileRequest) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_Instagram
}

func (x *RemoveFileRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *RemoveFileRequest) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *RemoveFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type UpdateCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MediaType              `protobuf:"varint,1,opt,name=type,proto3,enum=raker.v1.MediaType" json:"type,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Post          string                 `protobuf:"bytes,3,opt,name=post,proto3" json:"post,omitempty"`
	Categories    []string               `protobuf:"bytes,4,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoriesRequest) Reset() {
	*x = UpdateCategoriesRequest{}
	mi := &file_raker_v1_raker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoriesRequest) ProtoMessage() {}

func (x *UpdateCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoriesRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCategoriesRequest) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_Instagram
}

func (x *UpdateCategoriesRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *UpdateCategoriesRequest) GetPost() string {
	if x != nil {
		return x.Post
	}
	return ""
}

func (x *UpdateCategoriesRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Exclusive     bool                   `protobuf:"varint,2,opt,name=exclusive,proto3" json:"exclusive,omitempty"`
	Categories    []string               `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	Types         []MediaType            `protobuf:"varint,4,rep,packed,name=types,proto3,enum=raker.v1.MediaType" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_raker_v1_raker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{8}
}

func (x *HistoryRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *HistoryRequest) GetExclusive() bool {
	if x != nil {
		return x.Exclusive
	}
	return false
}

func (x *HistoryRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *HistoryRequest) GetTypes() []MediaType {
	if x != nil {
		return x.Types
	}
	return nil
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Histories     []*ScrapeResponse      `protobuf:"bytes,1,rep,name=histories,proto3" json:"histories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_raker_v1_raker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raker_v1_raker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_raker_v1_raker_proto_rawDescGZIP(), []int{9}
}

func (x *HistoryResponse) GetHistories() []*ScrapeResponse {
	if x != nil {
		return x.Histories
	}
	return nil
}

var File_raker_v1_raker_proto protoreflect.FileDescriptor

const file_raker_v1_raker_proto_rawDesc = "" +
	"\n" +
	"\x14raker/v1/raker.proto\x12\braker.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1agoogle/type/datetime.proto\x1a\x18google/type/latlng.proto\"\xa4\x01\n" +
	"\rSignUpRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\"\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tH\x00R\tsessionId\x88\x01\x01\x12\x1c\n" +
	"\auser_id\x18\x04 \x01(\tH\x01R\x06userId\x88\x01\x01B\r\n" +
	"\v_session_idB\n" +
	"\n" +
	"\b_user_id\"G\n" +
	"\rSignInRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"[\n" +
	"\x13EditCategoryRequest\x12!\n" +
	"\fold_category\x18\x01 \x01(\tR\voldCategory\x12!\n" +
	"\fnew_category\x18\x02 \x01(\tR\vnewCategory\"Y\n" +
	"\x12UnaryScrapeRequest\x12\x12\n" +
	"\x04post\x18\x01 \x01(\tR\x04post\x12!\n" +
	"\tincognito\x18\x02 \x01(\bH\x00R\tincognito\x88\x01\x01B\f\n" +
	"\n" +
	"_incognito\"p\n" +
	"\x13BinaryScrapeRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04post\x18\x02 \x01(\tR\x04post\x12!\n" +
	"\tincognito\x18\x03 \x01(\bH\x00R\tincognito\x88\x01\x01B\f\n" +
	"\n" +
	"_incognito\"\xe5\x02\n" +
	"\x0eScrapeResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x120\n" +
	"\tpost_type\x18\x02 \x01(\x0e2\x13.raker.v1.MediaTypeR\bpostType\x12\x1d\n" +
	"\n" +
	"post_owner\x18\x03 \x01(\tR\tpostOwner\x12\x12\n" +
	"\x04post\x18\x04 \x01(\tR\x04post\x122\n" +
	"\tpost_date\x18\x05 \x01(\v2\x15.google.type.DateTimeR\bpostDate\x12\x14\n" +
	"\x05files\x18\x06 \x03(\tR\x05files\x12\x1e\n" +
	"\n" +
	"categories\x18\a \x03(\tR\n" +
	"categories\x12\x1c\n" +
	"\tincognito\x18\b \x01(\bR\tincognito\x12:\n" +
	"\vcoordinates\x18\t \x01(\v2\x13.google.type.LatLngH\x00R\vcoordinates\x88\x01\x01B\x0e\n" +
	"\f_coordinates\"z\n" +
	"\x11RemoveFileRequest\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.raker.v1.MediaTypeR\x04type\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x12\n" +
	"\x04post\x18\x03 \x01(\tR\x04post\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"\x8c\x01\n" +
	"\x17UpdateCategoriesRequest\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.raker.v1.MediaTypeR\x04type\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x12\n" +
	"\x04post\x18\x03 \x01(\tR\x04post\x12\x1e\n" +
	"\n" +
	"categories\x18\x04 \x03(\tR\n" +
	"categories\"\x8f\x01\n" +
	"\x0eHistoryRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x1c\n" +
	"\texclusive\x18\x02 \x01(\bR\texclusive\x12\x1e\n" +
	"\n" +
	"categories\x18\x03 \x03(\tR\n" +
	"categories\x12)\n" +
	"\x05types\x18\x04 \x03(\x0e2\x13.raker.v1.MediaTypeR\x05types\"I\n" +
	"\x0fHistoryResponse\x126\n" +
	"\thistories\x18\x01 \x03(\v2\x18.raker.v1.ScrapeResponseR\thistories*J\n" +
	"\tMediaType\x12\r\n" +
	"\tInstagram\x10\x00\x12\r\n" +
	"\tHighlight\x10\x01\x12\t\n" +
	"\x05Story\x10\x02\x12\n" +
	"\n" +
	"\x06TikTok\x10\x03\x12\b\n" +
	"\x04VSCO\x10\x042\xa5\x06\n" +
	"\vRakerServer\x12B\n" +
	"\x0fSignUpInstagram\x12\x17.raker.v1.SignUpRequest\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\x0fSignInInstagram\x12\x17.raker.v1.SignUpRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\fEditCategory\x12\x1d.raker.v1.EditCategoryRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x0fScrapeInstagram\x12\x1c.raker.v1.UnaryScrapeRequest\x1a\x18.raker.v1.ScrapeResponse\x12I\n" +
	"\x0fScrapeHighlight\x12\x1c.raker.v1.UnaryScrapeRequest\x1a\x18.raker.v1.ScrapeResponse\x12E\n" +
	"\vScrapeStory\x12\x1c.raker.v1.UnaryScrapeRequest\x1a\x18.raker.v1.ScrapeResponse\x12G\n" +
	"\fScrapeTikTok\x12\x1d.raker.v1.BinaryScrapeRequest\x1a\x18.raker.v1.ScrapeResponse\x12E\n" +
	"\n" +
	"ScrapeVSCO\x12\x1d.raker.v1.BinaryScrapeRequest\x1a\x18.raker.v1.ScrapeResponse\x12C\n" +
	"\n" +
	"RemoveFile\x12\x1b.raker.v1.RemoveFileRequest\x1a\x18.raker.v1.ScrapeResponse\x12O\n" +
	"\x10UpdateCategories\x12!.raker.v1.UpdateCategoriesRequest\x1a\x18.raker.v1.ScrapeResponse\x12D\n" +
	"\rSearchHistory\x12\x18.raker.v1.HistoryRequest\x1a\x19.raker.v1.HistoryResponseB9Z7github.com/AppleGamer22/raker/server/buf/proto/raker/v1b\x06proto3"

var (
	file_raker_v1_raker_proto_rawDescOnce sync.Once
	file_raker_v1_raker_proto_rawDescData []byte
)

func file_raker_v1_raker_proto_rawDescGZIP() []byte {
	file_raker_v1_raker_proto_rawDescOnce.Do(func() {
		file_raker_v1_raker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raker_v1_raker_proto_rawDesc), len(file_raker_v1_raker_proto_rawDesc)))
	})
	return file_raker_v1_raker_proto_rawDescData
}

var file_raker_v1_raker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_raker_v1_raker_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_raker_v1_raker_proto_goTypes = []any{
	(MediaType)(0),                  // 0: raker.v1.MediaType
	(*SignUpRequest)(nil),           // 1: raker.v1.SignUpRequest
	(*SignInRequest)(nil),           // 2: raker.v1.SignInRequest
	(*EditCategoryRequest)(nil),     // 3: raker.v1.EditCategoryRequest
	(*UnaryScrapeRequest)(nil),      // 4: raker.v1.UnaryScrapeRequest
	(*BinaryScrapeRequest)(nil),     // 5: raker.v1.BinaryScrapeRequest
	(*ScrapeResponse)(nil),          // 6: raker.v1.ScrapeResponse
	(*RemoveFileRequest)(nil),       // 7: raker.v1.RemoveFileRequest
	(*UpdateCategoriesRequest)(nil), // 8: raker.v1.UpdateCategoriesRequest
	(*HistoryRequest)(nil),          // 9: raker.v1.HistoryRequest
	(*HistoryResponse)(nil),         // 10: raker.v1.HistoryResponse
	(*datetime.DateTime)(nil),       // 11: google.type.DateTime
	(*latlng.LatLng)(nil),           // 12: google.type.LatLng
	(*emptypb.Empty)(nil),           // 13: google.protobuf.Empty
}
var file_raker_v1_raker_proto_depIdxs = []int32{
	0,  // 0: raker.v1.ScrapeResponse.post_type:type_name -> raker.v1.MediaType
	11, // 1: raker.v1.ScrapeResponse.post_date:type_name -> google.type.DateTime
	12, // 2: raker.v1.ScrapeResponse.coordinates:type_name -> google.type.LatLng
	0,  // 3: raker.v1.RemoveFileRequest.type:type_name -> raker.v1.MediaType
	0,  // 4: raker.v1.UpdateCategoriesRequest.type:type_name -> raker.v1.MediaType
	0,  // 5: raker.v1.HistoryRequest.types:type_name -> raker.v1.MediaType
	6,  // 6: raker.v1.HistoryResponse.histories:type_name -> raker.v1.ScrapeResponse
	1,  // 7: raker.v1.RakerServer.SignUpInstagram:input_type -> raker.v1.SignUpRequest
	1,  // 8: raker.v1.RakerServer.SignInInstagram:input_type -> raker.v1.SignUpRequest
	3,  // 9: raker.v1.RakerServer.EditCategory:input_type -> raker.v1.EditCategoryRequest
	4,  // 10: raker.v1.RakerServer.ScrapeInstagram:input_type -> raker.v1.UnaryScrapeRequest
	4,  // 11: raker.v1.RakerServer.ScrapeHighlight:input_type -> raker.v1.UnaryScrapeRequest
	4,  // 12: raker.v1.RakerServer.ScrapeStory:input_type -> raker.v1.UnaryScrapeRequest
	5,  // 13: raker.v1.RakerServer.ScrapeTikTok:input_type -> raker.v1.BinaryScrapeRequest
	5,  // 14: raker.v1.RakerServer.ScrapeVSCO:input_type -> raker.v1.BinaryScrapeRequest
	7,  // 15: raker.v1.RakerServer.RemoveFile:input_type -> raker.v1.RemoveFileRequest
	8,  // 16: raker.v1.RakerServer.UpdateCategories:input_type -> raker.v1.UpdateCategoriesRequest
	9,  // 17: raker.v1.RakerServer.SearchHistory:input_type -> raker.v1.HistoryRequest
	13, // 18: raker.v1.RakerServer.SignUpInstagram:output_type -> google.protobuf.Empty
	13, // 19: raker.v1.RakerServer.SignInInstagram:output_type -> google.protobuf.Empty
	13, // 20: raker.v1.RakerServer.EditCategory:output_type -> google.protobuf.Empty
	6,  // 21: raker.v1.RakerServer.ScrapeInstagram:output_type -> raker.v1.ScrapeResponse
	6,  // 22: raker.v1.RakerServer.ScrapeHighlight:output_type -> raker.v1.ScrapeResponse
	6,  // 23: raker.v1.RakerServer.ScrapeStory:output_type -> raker.v1.ScrapeResponse
	6,  // 24: raker.v1.RakerServer.ScrapeTikTok:output_type -> raker.v1.ScrapeResponse
	6,  // 25: raker.v1.RakerServer.ScrapeVSCO:output_type -> raker.v1.ScrapeResponse
	6,  // 26: raker.v1.RakerServer.RemoveFile:output_type -> raker.v1.ScrapeResponse
	6,  // 27: raker.v1.RakerServer.UpdateCategories:output_type -> raker.v1.ScrapeResponse
	10, // 28: raker.v1.RakerServer.SearchHistory:output_type -> raker.v1.HistoryResponse
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_raker_v1_raker_proto_init() }
func file_raker_v1_raker_proto_init() {
	if File_raker_v1_raker_proto != nil {
		return
	}
	file_raker_v1_raker_proto_msgTypes[0].OneofWrappers = []any{}
	file_raker_v1_raker_proto_msgTypes[3].OneofWrappers = []any{}
	file_raker_v1_raker_proto_msgTypes[4].OneofWrappers = []any{}
	file_raker_v1_raker_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raker_v1_raker_proto_rawDesc), len(file_raker_v1_raker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raker_v1_raker_proto_goTypes,
		DependencyIndexes: file_raker_v1_raker_proto_depIdxs,
		EnumInfos:         file_raker_v1_raker_proto_enumTypes,
		MessageInfos:      file_raker_v1_raker_proto_msgTypes,
	}.Build()
	File_raker_v1_raker_proto = out.File
	file_raker_v1_raker_proto_goTypes = nil
	file_raker_v1_raker_proto_depIdxs = nil
}
