// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file raker/v1/webauthn/passkey.proto (package raker.v1.webauthn, syntax proto3)
/* eslint-disable */

// buf:lint:ignore PACKAGE_VERSION_SUFFIX

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file raker/v1/webauthn/passkey.proto.
 */
export const file_raker_v1_webauthn_passkey: GenFile = /*@__PURE__*/
  fileDesc("Ch9yYWtlci92MS93ZWJhdXRobi9wYXNza2V5LnByb3RvEhFyYWtlci52MS53ZWJhdXRobiImChJCZWdpblNpZ25VcFJlcXVlc3QSEAoIdXNlcm5hbWUYASABKAkiPwoTQmVnaW5TaWduVXBSZXNwb25zZRISCgpzZXNzaW9uX2lkGAEgASgJEhQKDG9wdGlvbnNfanNvbhgCIAEoCSJWChNGaW5pc2hTaWduVXBSZXF1ZXN0EhIKCnNlc3Npb25faWQYASABKAkSFAoMcGFzc2tleV9uYW1lGAIgASgJEhUKDXJlc3BvbnNlX2pzb24YAyABKAkiJgoSQmVnaW5TaWduSW5SZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJIj8KE0JlZ2luU2lnbkluUmVzcG9uc2USEgoKc2Vzc2lvbl9pZBgBIAEoCRIUCgxvcHRpb25zX2pzb24YAiABKAkiQAoTRmluaXNoU2lnbkluUmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJEhUKDXJlc3BvbnNlX2pzb24YAiABKAkiPAoUUmVuYW1lUGFzc2tleVJlcXVlc3QSEgoKcGFzc2tleV9pZBgBIAEoDBIQCghuZXdfbmFtZRgCIAEoCULNAQoVY29tLnJha2VyLnYxLndlYmF1dGhuQgxQYXNza2V5UHJvdG9QAVpAZ2l0aHViLmNvbS9BcHBsZUdhbWVyMjIvcmFrZXIvc2VydmVyL2J1Zi9wcm90by9yYWtlci92MS93ZWJhdXRobqICA1JWV6oCEVJha2VyLlYxLldlYmF1dGhuygIRUmFrZXJcVjFcV2ViYXV0aG7iAh1SYWtlclxWMVxXZWJhdXRoblxHUEJNZXRhZGF0YeoCE1Jha2VyOjpWMTo6V2ViYXV0aG5iBnByb3RvMw");

/**
 * @generated from message raker.v1.webauthn.BeginSignUpRequest
 */
export type BeginSignUpRequest = Message<"raker.v1.webauthn.BeginSignUpRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;
};

/**
 * Describes the message raker.v1.webauthn.BeginSignUpRequest.
 * Use `create(BeginSignUpRequestSchema)` to create a new message.
 */
export const BeginSignUpRequestSchema: GenMessage<BeginSignUpRequest> = /*@__PURE__*/
  messageDesc(file_raker_v1_webauthn_passkey, 0);

/**
 * @generated from message raker.v1.webauthn.BeginSignUpResponse
 */
export type BeginSignUpResponse = Message<"raker.v1.webauthn.BeginSignUpResponse"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string options_json = 2;
   */
  optionsJson: string;
};

/**
 * Describes the message raker.v1.webauthn.BeginSignUpResponse.
 * Use `create(BeginSignUpResponseSchema)` to create a new message.
 */
export const BeginSignUpResponseSchema: GenMessage<BeginSignUpResponse> = /*@__PURE__*/
  messageDesc(file_raker_v1_webauthn_passkey, 1);

/**
 * @generated from message raker.v1.webauthn.FinishSignUpRequest
 */
export type FinishSignUpRequest = Message<"raker.v1.webauthn.FinishSignUpRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string passkey_name = 2;
   */
  passkeyName: string;

  /**
   * @generated from field: string response_json = 3;
   */
  responseJson: string;
};

/**
 * Describes the message raker.v1.webauthn.FinishSignUpRequest.
 * Use `create(FinishSignUpRequestSchema)` to create a new message.
 */
export const FinishSignUpRequestSchema: GenMessage<FinishSignUpRequest> = /*@__PURE__*/
  messageDesc(file_raker_v1_webauthn_passkey, 2);

/**
 * @generated from message raker.v1.webauthn.BeginSignInRequest
 */
export type BeginSignInRequest = Message<"raker.v1.webauthn.BeginSignInRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;
};

/**
 * Describes the message raker.v1.webauthn.BeginSignInRequest.
 * Use `create(BeginSignInRequestSchema)` to create a new message.
 */
export const BeginSignInRequestSchema: GenMessage<BeginSignInRequest> = /*@__PURE__*/
  messageDesc(file_raker_v1_webauthn_passkey, 3);

/**
 * @generated from message raker.v1.webauthn.BeginSignInResponse
 */
export type BeginSignInResponse = Message<"raker.v1.webauthn.BeginSignInResponse"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string options_json = 2;
   */
  optionsJson: string;
};

/**
 * Describes the message raker.v1.webauthn.BeginSignInResponse.
 * Use `create(BeginSignInResponseSchema)` to create a new message.
 */
export const BeginSignInResponseSchema: GenMessage<BeginSignInResponse> = /*@__PURE__*/
  messageDesc(file_raker_v1_webauthn_passkey, 4);

/**
 * @generated from message raker.v1.webauthn.FinishSignInRequest
 */
export type FinishSignInRequest = Message<"raker.v1.webauthn.FinishSignInRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string response_json = 2;
   */
  responseJson: string;
};

/**
 * Describes the message raker.v1.webauthn.FinishSignInRequest.
 * Use `create(FinishSignInRequestSchema)` to create a new message.
 */
export const FinishSignInRequestSchema: GenMessage<FinishSignInRequest> = /*@__PURE__*/
  messageDesc(file_raker_v1_webauthn_passkey, 5);

/**
 * @generated from message raker.v1.webauthn.RenamePasskeyRequest
 */
export type RenamePasskeyRequest = Message<"raker.v1.webauthn.RenamePasskeyRequest"> & {
  /**
   * @generated from field: bytes passkey_id = 1;
   */
  passkeyId: Uint8Array;

  /**
   * @generated from field: string new_name = 2;
   */
  newName: string;
};

/**
 * Describes the message raker.v1.webauthn.RenamePasskeyRequest.
 * Use `create(RenamePasskeyRequestSchema)` to create a new message.
 */
export const RenamePasskeyRequestSchema: GenMessage<RenamePasskeyRequest> = /*@__PURE__*/
  messageDesc(file_raker_v1_webauthn_passkey, 6);

