// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file raker/v1/raker.proto (package raker.v1, syntax proto3)
/* eslint-disable */

import { RakerServer } from "./raker_pb";

/**
 * @generated from rpc raker.v1.RakerServer.SignUpInstagram
 */
export const signUpInstagram = RakerServer.method.signUpInstagram;

/**
 * @generated from rpc raker.v1.RakerServer.SignInInstagram
 */
export const signInInstagram = RakerServer.method.signInInstagram;

/**
 * @generated from rpc raker.v1.RakerServer.EditCategory
 */
export const editCategory = RakerServer.method.editCategory;

/**
 * @generated from rpc raker.v1.RakerServer.ScrapeInstagram
 */
export const scrapeInstagram = RakerServer.method.scrapeInstagram;

/**
 * @generated from rpc raker.v1.RakerServer.ScrapeHighlight
 */
export const scrapeHighlight = RakerServer.method.scrapeHighlight;

/**
 * @generated from rpc raker.v1.RakerServer.ScrapeStory
 */
export const scrapeStory = RakerServer.method.scrapeStory;

/**
 * @generated from rpc raker.v1.RakerServer.ScrapeTikTok
 */
export const scrapeTikTok = RakerServer.method.scrapeTikTok;

/**
 * @generated from rpc raker.v1.RakerServer.ScrapeSnapchat
 */
export const scrapeSnapchat = RakerServer.method.scrapeSnapchat;

/**
 * @generated from rpc raker.v1.RakerServer.ScrapeVSCO
 */
export const scrapeVSCO = RakerServer.method.scrapeVSCO;

/**
 * @generated from rpc raker.v1.RakerServer.RemoveFile
 */
export const removeFile = RakerServer.method.removeFile;

/**
 * @generated from rpc raker.v1.RakerServer.UpdateCategories
 */
export const updateCategories = RakerServer.method.updateCategories;

/**
 * @generated from rpc raker.v1.RakerServer.SearchHistory
 */
export const searchHistory = RakerServer.method.searchHistory;

/**
 * @generated from rpc raker.v1.RakerServer.SearchHistoryOwners
 */
export const searchHistoryOwners = RakerServer.method.searchHistoryOwners;
