// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: histories.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const historyAdd = `-- name: HistoryAdd :one
INSERT INTO Histories (
	username,
	type,
	owner,
	post,
	date,
	files,
	categories
) VALUES (
	$1::text,
	$2::text,
	$3::text,
	$4::text,
	NOW(),
	$5::text[],
	$6::text[]
) RETURNING username, type, owner, post, date, files, categories
`

type HistoryAddParams struct {
	Username   string
	Type       string
	Owner      string
	Post       string
	Files      []string
	Categories []string
}

func (q *Queries) HistoryAdd(ctx context.Context, arg HistoryAddParams) (History, error) {
	row := q.db.QueryRowContext(ctx, historyAdd,
		arg.Username,
		arg.Type,
		arg.Owner,
		arg.Post,
		pq.Array(arg.Files),
		pq.Array(arg.Categories),
	)
	var i History
	err := row.Scan(
		&i.Username,
		&i.Type,
		&i.Owner,
		&i.Post,
		&i.Date,
		pq.Array(&i.Files),
		pq.Array(&i.Categories),
	)
	return i, err
}

const historyGet = `-- name: HistoryGet :one
SELECT username, type, owner, post, date, files, categories FROM Histories WHERE type = $1::text AND post = $2::text
`

type HistoryGetParams struct {
	Type string
	Post string
}

func (q *Queries) HistoryGet(ctx context.Context, arg HistoryGetParams) (History, error) {
	row := q.db.QueryRowContext(ctx, historyGet, arg.Type, arg.Post)
	var i History
	err := row.Scan(
		&i.Username,
		&i.Type,
		&i.Owner,
		&i.Post,
		&i.Date,
		pq.Array(&i.Files),
		pq.Array(&i.Categories),
	)
	return i, err
}

const historyGetExclusive = `-- name: HistoryGetExclusive :many
SELECT username, type, owner, post, date, files, categories FROM Histories WHERE type = ANY($1::text[]) AND categories = $2::text[] AND OWNER LIKE $3::text
`

type HistoryGetExclusiveParams struct {
	Types      []string
	Categories []string
	Owner      string
}

func (q *Queries) HistoryGetExclusive(ctx context.Context, arg HistoryGetExclusiveParams) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, historyGetExclusive, pq.Array(arg.Types), pq.Array(arg.Categories), arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.Username,
			&i.Type,
			&i.Owner,
			&i.Post,
			&i.Date,
			pq.Array(&i.Files),
			pq.Array(&i.Categories),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const historyGetInclusive = `-- name: HistoryGetInclusive :many
SELECT username, type, owner, post, date, files, categories FROM Histories WHERE type = ANY($1::text[]) AND categories <@ $2::text[] AND OWNER LIKE $3::text
`

type HistoryGetInclusiveParams struct {
	Types      []string
	Categories []string
	Owner      string
}

// https://docs.sqlc.dev/en/stable/howto/select.html#passing-a-slice-as-a-parameter-to-a-query
// https://docs.sqlc.dev/en/stable/howto/named_parameters.html
func (q *Queries) HistoryGetInclusive(ctx context.Context, arg HistoryGetInclusiveParams) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, historyGetInclusive, pq.Array(arg.Types), pq.Array(arg.Categories), arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.Username,
			&i.Type,
			&i.Owner,
			&i.Post,
			&i.Date,
			pq.Array(&i.Files),
			pq.Array(&i.Categories),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const historyRemove = `-- name: HistoryRemove :exec
DELETE FROM Histories where type = $1::text AND owner = $2::text AND post = $3::text
`

type HistoryRemoveParams struct {
	Type  string
	Owner string
	Post  string
}

func (q *Queries) HistoryRemove(ctx context.Context, arg HistoryRemoveParams) error {
	_, err := q.db.ExecContext(ctx, historyRemove, arg.Type, arg.Owner, arg.Post)
	return err
}

const historyUpdateCategories = `-- name: HistoryUpdateCategories :exec
UPDATE Histories SET categories = $1::text[] WHERE post = $2::text AND post = $3::text
`

type HistoryUpdateCategoriesParams struct {
	Categories []string
	Type       string
	Post       string
}

func (q *Queries) HistoryUpdateCategories(ctx context.Context, arg HistoryUpdateCategoriesParams) error {
	_, err := q.db.ExecContext(ctx, historyUpdateCategories, pq.Array(arg.Categories), arg.Type, arg.Post)
	return err
}

const historyUpdateOwner = `-- name: HistoryUpdateOwner :exec
UPDATE Histories SET owner = $1::text WHERE post = $2::text AND owner = $3::text
`

type HistoryUpdateOwnerParams struct {
	OldOwner string
	Type     string
	NewOwner string
}

func (q *Queries) HistoryUpdateOwner(ctx context.Context, arg HistoryUpdateOwnerParams) error {
	_, err := q.db.ExecContext(ctx, historyUpdateOwner, arg.OldOwner, arg.Type, arg.NewOwner)
	return err
}

const updateHistoryRemoveFile = `-- name: UpdateHistoryRemoveFile :exec
UPDATE Histories SET files = array_remove(files, $1::text) WHERE post = $2::text AND post = $3::text
`

type UpdateHistoryRemoveFileParams struct {
	File string
	Type string
	Post string
}

func (q *Queries) UpdateHistoryRemoveFile(ctx context.Context, arg UpdateHistoryRemoveFileParams) error {
	_, err := q.db.ExecContext(ctx, updateHistoryRemoveFile, arg.File, arg.Type, arg.Post)
	return err
}
