// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	HistoriesCategoryRename(ctx context.Context, arg HistoriesCategoryRenameParams) error
	HistoryAdd(ctx context.Context, arg HistoryAddParams) (History, error)
	HistoryAddFromArchive(ctx context.Context, arg HistoryAddFromArchiveParams) (History, error)
	HistoryCount(ctx context.Context, arg HistoryCountParams) (int64, error)
	HistoryCountByFile(ctx context.Context, arg HistoryCountByFileParams) (int64, error)
	HistoryGet(ctx context.Context, arg HistoryGetParams) (History, error)
	HistoryGetByOwner(ctx context.Context, arg HistoryGetByOwnerParams) (History, error)
	// https://docs.sqlc.dev/en/stable/howto/select.html#passing-a-slice-as-a-parameter-to-a-query
	// https://docs.sqlc.dev/en/stable/howto/named_parameters.html
	HistoryGetPage(ctx context.Context, arg HistoryGetPageParams) ([]History, error)
	HistoryOwners(ctx context.Context, arg HistoryOwnersParams) ([]HistoryOwnersRow, error)
	HistoryRemove(ctx context.Context, arg HistoryRemoveParams) error
	HistoryUpdateCategories(ctx context.Context, arg HistoryUpdateCategoriesParams) (History, error)
	HistoryUpdateOwner(ctx context.Context, arg HistoryUpdateOwnerParams) error
	UpdateHistoryRemoveFile(ctx context.Context, arg UpdateHistoryRemoveFileParams) (History, error)
	UserAdd(ctx context.Context, arg UserAddParams) error
	UserCategoryAdd(ctx context.Context, arg UserCategoryAddParams) error
	UserCategoryRemove(ctx context.Context, arg UserCategoryRemoveParams) error
	UserGet(ctx context.Context, username string) (User, error)
	UserUpdateHash(ctx context.Context, arg UserUpdateHashParams) error
	UserUpdateInstagramSession(ctx context.Context, arg UserUpdateInstagramSessionParams) error
}

var _ Querier = (*Queries)(nil)
