// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const passkeyUpdateName = `-- name: PasskeyUpdateName :exec
UPDATE
	Passkeys
SET
	name = $1::text
WHERE
	id = $2::bytea
`

type PasskeyUpdateNameParams struct {
	Name      string `json:"name"`
	PasskeyID []byte `json:"passkey_id"`
}

func (q *Queries) PasskeyUpdateName(ctx context.Context, arg PasskeyUpdateNameParams) error {
	_, err := q.exec(ctx, q.passkeyUpdateNameStmt, passkeyUpdateName, arg.Name, arg.PasskeyID)
	return err
}

const passkeyUpdateSignCount = `-- name: PasskeyUpdateSignCount :exec
UPDATE
	Passkeys
SET
	sign_count = sign_count + 1
WHERE
	id = $1::bytea
`

func (q *Queries) PasskeyUpdateSignCount(ctx context.Context, passkeyID []byte) error {
	_, err := q.exec(ctx, q.passkeyUpdateSignCountStmt, passkeyUpdateSignCount, passkeyID)
	return err
}

const userAdd = `-- name: UserAdd :exec
INSERT INTO Users(
	username,
	password_hash,
	instagram_session_id,
	instagram_user_id,
	network,
	categories)
VALUES (
	$1::text,
	$2::text,
	$3::text,
	$4::text,
	'instagram',
	$5::text[])
`

type UserAddParams struct {
	Username           string   `json:"username"`
	PasswordHash       string   `json:"password_hash"`
	InstagramSessionID string   `json:"instagram_session_id"`
	InstagramUserID    string   `json:"instagram_user_id"`
	Categories         []string `json:"categories"`
}

func (q *Queries) UserAdd(ctx context.Context, arg UserAddParams) error {
	_, err := q.exec(ctx, q.userAddStmt, userAdd,
		arg.Username,
		arg.PasswordHash,
		arg.InstagramSessionID,
		arg.InstagramUserID,
		pq.Array(arg.Categories),
	)
	return err
}

const userCategoryAdd = `-- name: UserCategoryAdd :exec
UPDATE
	Users
SET
	categories = ARRAY (
		SELECT
			unnest(array_append(categories, $1::text)) AS c
		ORDER BY
			c)
	WHERE
		username = $2::text
`

type UserCategoryAddParams struct {
	Category string `json:"category"`
	Username string `json:"username"`
}

func (q *Queries) UserCategoryAdd(ctx context.Context, arg UserCategoryAddParams) error {
	_, err := q.exec(ctx, q.userCategoryAddStmt, userCategoryAdd, arg.Category, arg.Username)
	return err
}

const userCategoryRemove = `-- name: UserCategoryRemove :exec
UPDATE
	Users
SET
	categories = array_remove(categories, $1::text)
WHERE
	username = $2::text
`

type UserCategoryRemoveParams struct {
	Category string `json:"category"`
	Username string `json:"username"`
}

func (q *Queries) UserCategoryRemove(ctx context.Context, arg UserCategoryRemoveParams) error {
	_, err := q.exec(ctx, q.userCategoryRemoveStmt, userCategoryRemove, arg.Category, arg.Username)
	return err
}

const userCreatePasskey = `-- name: UserCreatePasskey :exec
INSERT INTO Passkeys(
	id,
	user_id,
	name,
	public_key,
	attestation_type,
	aaguid,
	transports)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7)
`

type UserCreatePasskeyParams struct {
	PasskeyID       []byte    `json:"passkey_id"`
	UdserID         uuid.UUID `json:"udser_id"`
	Name            string    `json:"name"`
	PublicKey       []byte    `json:"public_key"`
	AttestationType string    `json:"attestation_type"`
	Aaguid          []byte    `json:"aaguid"`
	Transports      []string  `json:"transports"`
}

func (q *Queries) UserCreatePasskey(ctx context.Context, arg UserCreatePasskeyParams) error {
	_, err := q.exec(ctx, q.userCreatePasskeyStmt, userCreatePasskey,
		arg.PasskeyID,
		arg.UdserID,
		arg.Name,
		arg.PublicKey,
		arg.AttestationType,
		arg.Aaguid,
		pq.Array(arg.Transports),
	)
	return err
}

const userGet = `-- name: UserGet :one
SELECT
	username, password_hash, instagram_session_id, instagram_user_id, network, categories, tiktok_session_id, tiktok_session_id_guard, id
FROM
	Users
WHERE
	username = $1::text
`

func (q *Queries) UserGet(ctx context.Context, username string) (User, error) {
	row := q.queryRow(ctx, q.userGetStmt, userGet, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.PasswordHash,
		&i.InstagramSessionID,
		&i.InstagramUserID,
		&i.Network,
		pq.Array(&i.Categories),
		&i.TiktokSessionID,
		&i.TiktokSessionIDGuard,
		&i.ID,
	)
	return i, err
}

const userGetPasskeysByUsername = `-- name: UserGetPasskeysByUsername :many
SELECT
	id, name, user_id, public_key, attestation_type, aaguid, sign_count, transports
FROM
	passkeys
WHERE
	username = $1::text
`

func (q *Queries) UserGetPasskeysByUsername(ctx context.Context, username string) ([]Passkey, error) {
	rows, err := q.query(ctx, q.userGetPasskeysByUsernameStmt, userGetPasskeysByUsername, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Passkey
	for rows.Next() {
		var i Passkey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.PublicKey,
			&i.AttestationType,
			&i.Aaguid,
			&i.SignCount,
			pq.Array(&i.Transports),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userUpdateHash = `-- name: UserUpdateHash :exec
UPDATE
	Users
SET
	password_hash = $1::text
WHERE
	username = $2::text
`

type UserUpdateHashParams struct {
	PasswordHash string `json:"password_hash"`
	Username     string `json:"username"`
}

func (q *Queries) UserUpdateHash(ctx context.Context, arg UserUpdateHashParams) error {
	_, err := q.exec(ctx, q.userUpdateHashStmt, userUpdateHash, arg.PasswordHash, arg.Username)
	return err
}

const userUpdateInstagramSession = `-- name: UserUpdateInstagramSession :exec
UPDATE
	Users
SET
	instagram_session_id = $1::text,
	instagram_user_id = $2::text,
	password_hash = $3::text
WHERE
	username = $4::text
`

type UserUpdateInstagramSessionParams struct {
	InstagramSessionID string `json:"instagram_session_id"`
	InstagramUserID    string `json:"instagram_user_id"`
	PasswordHash       string `json:"password_hash"`
	Username           string `json:"username"`
}

func (q *Queries) UserUpdateInstagramSession(ctx context.Context, arg UserUpdateInstagramSessionParams) error {
	_, err := q.exec(ctx, q.userUpdateInstagramSessionStmt, userUpdateInstagramSession,
		arg.InstagramSessionID,
		arg.InstagramUserID,
		arg.PasswordHash,
		arg.Username,
	)
	return err
}
